### ISSUE TITLE
[Question] What does the spec.pvc.resources.requests.storage value in datavolume.yaml means in vm?

### ISSUE THREAD

**Issue by anencore94** [kubevirt/containerized-data-importer#1150]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
I need some help for my misunderstanding.
I wonder what does the value in spec.pvc.resources.requests.storage when kind:DataVolume yaml.

When i make a datavolume with "https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.0-i386-disk.img", the qemu-img info for this image is as belows:
```
$ qemu-img info cirros-0.3.0-i386-disk.img 

image: cirros-0.3.0-i386-disk.img
file format: qcow2
virtual size: 39M (41126400 bytes)
disk size: 8.7M
cluster_size: 65536
Format specific information:
    compat: 0.10
    refcount bits: 16
```

But, when after i created datavolume with this yaml below,
```
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: my-data-volume
spec:
  source:
      http:
         url: "https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.0-i386-disk.img"
  pvc:
    storageClassName: csi-cephfs-sc
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
```
And create vm with this yaml below,
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: vm1
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: my-data-volume
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: vm1
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtSxD8ss5we8LCTge84WLHbiac+qlG8MH+4c6ItSZHnzQJ6cbqokFkO7mpbtfRIVcJ+1E7rzl0DcmvTtUTzYOaf3C5nw2GMjDE1Kh38KzSveSg1mAhQba/h1e7xH64fYFEK/sftZBCZOStPm5Ho2VfTSv5DaV3YDZYQ8ax22z7NWzguDs61nf/cj7owL5WXylD6O0q5hZh1qSUrJ0POK87b6JSuCH3aKTRQeSq4d6z9htHGXFnxEKf0EQueVOCjaS4L6FdHhmHlqzqGoAvWMOvTgLqneQw0+afUxBhUqr/HJ4g4E0q8pjbd61KSm6riEqf9PcwYuFcyCZiIx46B00T kjy@kjy-B360M-D3H
        name: cloudinitdisk
```

**What you expected to happen**:

Then when i exec on virt-launcher pod and access my image in `/run/kubevirt-private/vmi-disks/disk0/disk.img`, the img size was not fit as i expected, see the img size as belows:
```
[root@vm1 disk0]# qemu-img info disk.img 
image: disk.img
file format: raw
virtual size: 5.0G (5368709120 bytes)
disk size: 5.0G

-------------------------------------------
[root@vm1 /]# df -h
Filesystem                                                                     Size  Used Avail Use% Mounted on
overlay                                                                         33G   13G   19G  40% /
tmpfs                                                                           64M     0   64M   0% /dev
tmpfs                                                                          1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/vda1                                                                       33G   13G   19G  40% /etc/hosts
shm                                                                             64M     0   64M   0% /dev/shm
tmpfs                                                                          1.9G   12M  1.9G   1% /run/kubevirt
10.110.240.183:6789:/volumes/csi/csi-vol-a8520756-69a1-11ea-86b1-0242ac110008  5.0G  5.0G     0 100% /run/kubevirt-private/vmi-disks/disk0
tmpfs                                                                          1.9G     0  1.9G   0% /proc/acpi
tmpfs                                                                          1.9G     0  1.9G   0% /proc/scsi
tmpfs                                                                          1.9G     0  1.9G   0% /sys/firmware

```
I expected that the virtual size should be 5.0G, but disk size will be much much smaller same as original image file. And there will be some space that vm can use.

Also, when i access to vm, there was no space that i expected (actually, i thought '5.0GB - imageSize'-sized-disk should be mounted on `/root/` in vm)
```
$ df -h
Filesystem                Size      Used Available Use% Mounted on
/dev                    476.4M         0    476.4M   0% /dev
tmpfs                   477.6M         0    477.6M   0% /dev/shm
tmpfs                   200.0K     12.0K    188.0K   6% /run
```

I think maybe I misunderstood something wrong.. But I can't figure out for now.
I'll be really appreciated if anybody tell me what does that storage-size value mean and what should i do if i want to use some space as root file system for created-vm.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Thank you for your help.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
v1.13.0

- Kubernetes version (use `kubectl version`):
v1.17.2 (minikube - kvm2 driver option)

- Cloud provider or hardware configuration:
- Install tools:
- Others:
rook version : v1.2.4
kubevirt version : v0.23.0
