### ISSUE TITLE
imageio source does not show progress

### ISSUE THREAD

**Issue by suomiy** [kubevirt/containerized-data-importer#1190]
/kind enhancement

**What happened**:
The import is progressing (progress can be seen in ovirt webadmin and the size of imported disk is getting larger), but DataVolume CR doesn't show progress and stays: `N/A`

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: e0e9ac82-6876-4383-a6ec-254142d9d139
  namespace: default254142d9d139
  uid: d8b94e20-abeb-4a54-8186-c18fa65fa980
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 12Gi
  source:
    imageio:
      certConfigMap: vmimport.v2v.kubevirt.io2n7jl
      diskId: e0e9ac82-6876-4383-a6ec-254142d9d139
      secretRef: vmimport.v2v.kubevirt.iortgpw
      url: 'https://mburman-4-test-rpms.scl.lab.tlv.redhat.com/ovirt-engine/api'
status:
  phase: ImportInProgress
  progress: N/A
  restartCount: 0

```

**Environment**:
- CDI version: v1.16.0
- Kubernetes version:
```js
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"archive", BuildDate:"2020-04-19T14:21:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"aa10b5b", GitTreeState:"clean", BuildDate:"2020-03-16T18:11:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
