### ISSUE TITLE
Creating a DataVolume using `Mi` unit

### ISSUE THREAD

**Issue by hyoung-90** [kubevirt/containerized-data-importer#1341]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When I create datavolume using `Mi` unit, the status of datavolume is not updated. Only for the value divided by 1024 like 4096, 5120.
I got the following error in cdi-apiserver pod log.
```
E0818 01:49:34.399376       1 datavolume-validate.go:251] Cannot update spec for DataVolume default/dv
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- create datavolume using `Mi` unit
```yaml
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: dv
spec:
  source:
    http:
      url: "https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.0-i386-disk.img"
  pvc:
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5120Mi
```

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
  - Tested on both version:
    - v1.11.0
    - v1.18.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- Install tools:
- Others:
