### ISSUE TITLE
cdi rbac roles

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#136]
The advice in the primary README.md to bind the default service account for a namespace with cluster-admin privileges isn't wise. Even with the disclaimer, we don't want that accidentally replicated.

For example, I already see that kubevirt-ansible is using this method to deploy CDI right now. I'd hate for something like this to accidentally make it's way into production someday. 

## short term fix
As a short term method, we'd be better off giving the CDI deployment a service-account with cluster-admin roles rather than binding cluster-admin to the default account in a namespace. 

I'd recommend making this change asap before CDI gains any more traction. 

### long term fix
add a ServiceAccount, RBAC ClusterRole, and ClusterRoleBinding into a manifest and make the cdi-controller-deployment.yaml reference the service account. 

The kubevirt manifest has some examples of how we do this for our controllers. 
https://github.com/kubevirt/kubevirt/blob/master/manifests/release/kubevirt.yaml.in

**Comment by davidvossel** [comment]
I didn't test this but something similar should work as a short term solution

```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cdi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cdi-sa
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cdi-sa
    namespace: default
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cdi-deployment
  labels:
    app: containerized-data-importer
spec:
  selector:
    matchLabels:
      app: containerized-data-importer
  replicas: 1
  template:
    metadata:
      labels:
        app: containerized-data-importer
    spec:
      serviceAccountName: cdi-sa
      containers:
      - name: cdi-controller
        image: kubevirt/cdi-controller
        imagePullPolicy: IfNotPresent
```
