### ISSUE TITLE
Cannot set certConfigmap for s3 source

### ISSUE THREAD

**Issue by gitlawr** [kubevirt/containerized-data-importer#1506]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
[Documentation](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/datavolumes.md#https3registry-source) says the certConfigMap option is available for HTTP/S3/Registry source. However, it is not implemented for S3.

The validation fails when this field is set:
```
error: error validating "dv.yaml": error validating data: ValidationError(DataVolume.spec.source.s3): unknown field "certConfigMap" in io.kubevirt.cdi.v1beta1.DataVolume.spec.source.s3; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Create a data volume:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: mydv
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
  source:
    s3:
      url: xxxxx
      secretRef: s3
      certConfigMap: import-certs
```

**Environment**:
- CDI version: v1.26.1
