### ISSUE TITLE
Cannot clone DV: Source contentType () and target contentType (kubevirt) do not match

### ISSUE THREAD

**Issue by brybacki** [kubevirt/containerized-data-importer#1656]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Error "Source contentType () and target contentType (kubevirt) do not match" for field "spec.PVC". when cloning PVC

**What you expected to happen**:
Success

**How to reproduce it (as minimally and precisely as possible)**:
Create a DV (for example importing containerdisk):

```yaml
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: dv-src
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  source:
    registry:
      url: docker://quay.io/kubevirt/cirros-container-disk-demo
```

Create a clone DV:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-tgt 
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
  source:
    pvc:
      name: dv-src
      namespace: default
```
Result is:

```
Error from server: error when creating "dv-clone.yaml": admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request:  Source contentType () and target contentType (kubevirt) do not match
```

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.30.0
- Kubernetes version (use `kubectl version`):v1.18.14"
- Cloud provider or hardware configuration:
- Install tools:
- Others:

After a quick investigation I suppose it might be something with handling default values here: `pkg/apiserver/webhooks/datavolume-validate.go:validateContentTypes `
