### ISSUE TITLE
CDI has a default pod resource request/limit that is incompatible with LimitRange and ResourceQuota

### ISSUE THREAD

**Issue by kincl** [kubevirt/containerized-data-importer#1666]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

CDIConfig out of the box ships with a very odd default pod resource request/limit config[1] that doesn't work with a namespace using ResourceQuotas and LimitRanges.

[1]
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDIConfig
metadata:
  name: config
spec: {}
status:
  defaultPodResourceRequirements:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
```

This creates CDI importer pods with a limits and requests both at zero which fail to create if a LimitRange is set.

**What you expected to happen**:

CDI importer pods are created regardless of ResourceQuota or LimitRange defaults

**How to reproduce it (as minimally and precisely as possible)**:

Create a LimitRange and ResourceQuota in a namespace:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - default:
      cpu: 300m
      memory: 500Mi
    defaultRequest:
      cpu: 300m
      memory: 500Mi
    maxLimitRequestRatio:
      cpu: "10"
    type: Container
```

Try to create a VM object that requires a CDI data import:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: test
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: test-rootdisk-087mt
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
        volumeMode: Filesystem
      source:
        http:
          url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2
    status: {}
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: cloudinitdisk
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.1.0
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: test
      networks:
      - name: nic-0
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: test-rootdisk-087mt
        name: rootdisk
```

The CDI controller will be unable to create a pod in the namespace.

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
v1.23
- Kubernetes version (use `kubectl version`):
1.19
