### ISSUE TITLE
Add access to secrets for RBAC

### ISSUE THREAD

**Issue by screeley44** [kubevirt/containerized-data-importer#178]
```
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create"]
```
