### ISSUE TITLE
DataVolume PVC in pending state

### ISSUE THREAD

**Issue by k-p-ani** [kubevirt/containerized-data-importer#1802]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind enhancement

**What happened**:
I have Kubernetes deployed on BareMeta and storage used is local storage attached to the bare metal and there is no **default** storage class defined. In this situation  DataVolume and corresponding PVC stays in pending state. If I mark one of the storage class as default by patching it, then DataVolume and corresponding PVC create successfully and image get imported.

Below is my DataVolume yam file
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: centos-7-cloud-base
spec:
  source:
    registry:
      url: "docker://quay.io/my-repo/my-image:latest"
      secretRef: my-pull-secret
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi

Storage classes available in the platform are
**apiVersion: storage.k8s.io/v1
kind: StorageClass**
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"anthos-system"},"provisioner":"kubernetes.io/no-provisioner","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
  name: anthos-system
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

**apiVersion: storage.k8s.io/v1
kind: StorageClass**
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-disks"},"provisioner":"kubernetes.io/no-provisioner","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
  name: local-disks
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

**apiVersion: storage.k8s.io/v1
kind: StorageClass**
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-shared"},"provisioner":"kubernetes.io/no-provisioner","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
  name: local-shared
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

**What you expected to happen**:
if default storage class not exists, then a way to suggest DataVolume which storage class to be used while it create PVC

**How to reproduce it (as minimally and precisely as possible)**:
Setup CDI on any kubernetes, make sure there is **no default storage class defined**. Then create DataVolume and check the status of DataVolume

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.34.0
- Kubernetes version (use `kubectl version`): Google Anthos 1.6.2
- Cloud provider or hardware configuration: bare-metal with Ubuntu as OS
- Install tools:
- Others:

**Comment by awels** [comment]
You can specify the storage class in the pvc (or if using 1.34 or newer, also storage) part of the spec. For example
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: example-blank
spec:
  source:
    blank: {}
  pvc:
    storageClassName: local
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
```

**Comment by awels** [comment]
Storage example:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: example-blank
spec:
  source:
    blank: {}
  storage:
    storageClassName: local
    resources:
      requests:
        storage: 5Gi
```

This assumes the storage profile for the 'local' storage class is valid and has the recommended values.
