### ISSUE TITLE
Support for Externally managed certificates for CDI components

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/containerized-data-importer#1829]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

This is a feature request for supporting externally managed certificates for CDI.  There should be an option to turn off Virt-operator's certs management for CDI components. The users should be able to specify an externally managed certs. To support this feature I envision following changes.

1. Support to turn on/off Virt operator cert generation and management by adding field to CDI CR:
The CDI CR can be used as shown below to enable or disable cert management by Virt-operator
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  imagePullPolicy: IfNotPresent
  certificateStrategy:
    externallyManaged: true
```
2. Support to specify customization of CDI deployments created by virt-operator
For external cert management there might be requirement to add different mounts than the ones added by default on all the deployment. Also this feature can be used to add various other customization to CDI deployments. It will be similar to [this](https://github.com/kubevirt/kubevirt/pull/3612) PR on Kubevirt 

3. Support to specify customized cert paths for apiserver, controller and uploadproxy.
The custom cert paths will be set by the functionality mentioned in above in 2. Apiserver, controller and uploadproxy need to consume these custom cert paths. [PR](https://github.com/kubevirt/containerized-data-importer/pull/1820) address this.
