### ISSUE TITLE
cdi-controller in crashing because certain type of ingress objects

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/containerized-data-importer#1868]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
cdi-controller fails with following error
```
 E0722 23:32:40.307785       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1543 [running]:
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x171f060, 0x29b6db0)
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x171f060, 0x29b6db0)
  GOROOT/src/runtime/panic.go:969 +0x166
kubevirt.io/containerized-data-importer/pkg/controller.getURLFromIngress(0xc003ee4310, 0xc000044044, 0xf, 0x0, 0x0)
  pkg/controller/config-controller.go:600 +0x204
kubevirt.io/containerized-data-importer/pkg/controller.watchIngress.func2(0x1bc3780, 0xc003ee4310, 0x1bc3780)
  pkg/controller/config-controller.go:533 +0x64
kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Create(...)
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:71
kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd(0x1b92f80, 0xc000542a58, 0x1baadc0, 0xc000a7a480, 0xc00099bf90, 0x1, 0x1, 0x18e76e0, 0xc003ee4310)
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go:57 +0xd1
kubevirt.io/containerized-data-importer/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0x129
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000617760)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00033ef60, 0x1b55bc0, 0xc002d92000, 0x16e8801, 0xc002d5c000)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000617760, 0x3b9aca00, 0x0, 0xc002d4c001, 0xc002d5c000)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
kubevirt.io/containerized-data-importer/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000860180)
  vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002f27d0, 0xc0027e2ae0)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1583084]

goroutine 1543 [running]:
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x171f060, 0x29b6db0)
  GOROOT/src/runtime/panic.go:969 +0x166
kubevirt.io/containerized-data-importer/pkg/controller.getURLFromIngress(0xc003ee4310, 0xc000044044, 0xf, 0x0, 0x0)
  pkg/controller/config-controller.go:600 +0x204
kubevirt.io/containerized-data-importer/pkg/controller.watchIngress.func2(0x1bc3780, 0xc003ee4310, 0x1bc3780)
  pkg/controller/config-controller.go:533 +0x64
kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Create(...)
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:71
kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd(0x1b92f80, 0xc000542a58, 0x1baadc0, 0xc000a7a480, 0xc00099bf90, 0x1, 0x1, 0x18e76e0, 0xc003ee4310)
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go:57 +0xd1
kubevirt.io/containerized-data-importer/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0x129
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000617760)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d8df60, 0x1b55bc0, 0xc002d92000, 0x16e8801, 0xc002d5c000)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000617760, 0x3b9aca00, 0x0, 0xc002d4c001, 0xc002d5c000)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
kubevirt.io/containerized-data-importer/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000860180)
  vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002f27d0, 0xc0027e2ae0)
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by kubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62
```
When there is an ingress object as below on the cluster which has `Spec.DefaultBackend.Service` as empty then we hit the error
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.org/ssl-services: "cdi-uploadproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  defaultBackend:
    resource:
      apiGroup: test.test
      kind: test
      name: test
  tls:
  - hosts:
    # change to a valid FQDN in your organization
    - cdi-uploadproxy.example.com
```
It happening because [this](https://github.com/kubevirt/containerized-data-importer/blob/466f706bf190a03431653107a430ab509b5b62f9/pkg/controller/config-controller.go#L600) check.

I am not sure why we need to iterate through all the ingress objects on cluster
**What you expected to happen**:
cdi-controller should run without error

**How to reproduce it (as minimally and precisely as possible)**:
Run cdi with following ingress object on cluster
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.org/ssl-services: "cdi-uploadproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  defaultBackend:
    resource:
      apiGroup: test.test
      kind: test
      name: test
  tls:
  - hosts:
    # change to a valid FQDN in your organization
    - cdi-uploadproxy.example.com
```
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
v1.36.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:
