### ISSUE TITLE
Allow custom TLS certificate for upload proxy

### ISSUE THREAD

**Issue by shosti** [kubevirt/containerized-data-importer#1968]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

I've exposed the CDI upload proxy as a `LoadBalancer` service for direct uploads without a reverse proxy (since I was running into issues with CDI behind nginx). I've mapped a DNS name (e.g. `cdi-upload.my.domain`) to the LoadBalancer's external IP address.

Unfortunately, the CDI operator seems to automatically provision a TLS certificate which uses its own CA and doesn't match the DNS name I've set, so I have to use the `--insecure` flag when uploading any images. I tried creating a certificate with cert manager (writing a certificate to the `cdi-uploadproxy-tls` secret), but the CDI operator seems to overwrite that secret periodically.

**What you expected to happen**:

I'd like to be able to provide a custom TLS certificate to the CDI upload proxy (if this is already possible, please let me know). Ideally this would be something in the `CDI` CRD (something like `spec.certConfig.uploadProxy.tlsSecret`), but I'd be fine with any documented solution.

**Anything else we need to know?**:

**Environment**:
- CDI version: 1.39.0
- Kubernetes version: 1.22.2
- Cloud provider or hardware configuration: Self-hosted
- Install tools: kustomize/FluxCD

**Comment by awels** [comment]
@mhenriks You have an ideas on this?

**Comment by awels** [comment]
I am kind of confused, wouldn't your custom cert be part of the load balancer, and then the load balancer will re-encrypt when communicating with the upload proxy. This will allow CDI to rotate its certs at its pace while your load balancer can rotate at its own pace as well.

**Comment by mhenriks** [comment]
@awels @shosti mentions that there is no revers proxy in front of cdi-uploadproxy in this config.  In openshift, this would be considered a "passthrough" route rather than "reencrypt" which is what we kind of assume

**Comment by jrcichra** [comment]
I took a different approach to solving this problem. You can specify a patch like this on `customizeComponents` on the CDI spec:

```yaml
      - patch: '{"spec":{"template":{"spec":{"$setElementOrder/volumes":[{"name":"server-cert"},{"name":"client-cert"}],"volumes":[{"$retainKeys":["name","secret"],"name":"server-cert","secret":{"secretName":"your-custom-certificate"}}]}}}}'
        resourceName: cdi-uploadproxy
        resourceType: Deployment
        type: strategic
```

I generated this with `kubectl edit deploy cdi-uploadproxy --output-patch`.
