### ISSUE TITLE
Pods should have seccompProfile RuntimeDefault

### ISSUE THREAD

**Issue by haslersn** [kubevirt/containerized-data-importer#2073]
/kind bug

**What happened**:

In my K8s 1.19 cluster which implements [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) with default Restricted, the ControllerManager fails to create Pods for the operator and, when manually working around that issue, the operator fails to create the apiserver, deployment, uploadproxy and importers due to:

```
PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden:  is not an allowed seccomp profile. Valid values are docker/default,runtime/default
```

**What you expected to happen**:

Both the recommended installation (cdi-operator.yaml) and the operator itself should add

```
securityContext:
  seccompProfile:
    type: RuntimeDefault
```

to all PodSpecs including importers deployed in other namespaces. (This is required previous to Kubernetes 1.22 where the `SeccompDefault` feature gate hits alpha.)

**Workaround**:

As a less secure workaround, one can add the following:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-baseline
rules:
  - apiGroups: [policy]
    resources: [podsecuritypolicies]
    verbs: [use]
    resourceNames: [baseline]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-cdi-baseline
roleRef:
  kind: ClusterRole
  name: psp-baseline
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts:cdi
    apiGroup: rbac.authorization.k8s.io
```

**Environment**:
- CDI version: 1.42.1
- Kubernetes version: 1.19
- Cloud provider or hardware configuration: kubeadm on Debian 10
