### ISSUE TITLE
Token is expired when clone a datavolume from a pvc in another namespace

### ISSUE THREAD

**Issue by tiezhuoyu** [kubevirt/containerized-data-importer#2074]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Token is expired when clone a datavolume from a pvc in another namespace. 

**What you expected to happen**:
Successfully clone a datavolume from a pvc in another namespace.

**How to reproduce it (as minimally and precisely as possible)**:

clone a dv from a pvc in another namespace.
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cs-tzy-test-2
  namespace: test-39c81efd691448c3a330e181ab960bc8
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: csi-rbd-nbd 
    volumeMode: Block
  source:
    pvc:
      name: rbd-dv-cirros 
      namespace: default 
```

After that, dv cs-tzy-test-2 is hung, and no pvc or importer is created. 
I check the log of controller, and it show that the token of dv is expired.

```
{"level":"info","ts":1640836213.942551,"logger":"controller.datavolume-controller","msg":"Initializing transfer","Datavolume":"test-39c81efd691448c3a330e181ab960bc8/cs-test2"}
{"level":"error","ts":1640836213.9431422,"logger":"controller-runtime.manager.controller.datavolume-controller","msg":"Reconciler error","name":"cs-test2","namespace":"test-39c81efd691448c3a330e181ab960bc8","error":"error verifying token: square/go-jose/jwt: validation failed, token is expired (exp)","errorVerbose":"square/go-jose/jwt: validation failed, token is expired (exp)\nerror verifying token\nkubevirt.io/containerized-data-importer/pkg/controller.validateCloneTokenDV\n\tpkg/controller/util.go:861\nkubevirt.io/containerized-data-importer/pkg/controller.(*DatavolumeReconciler).initTransfer\n\tpkg/controller/datavolume-controller.go:1111\nkubevirt.io/containerized-data-importer/pkg/controller.(*DatavolumeReconciler).doCrossNamespaceClone\n\tpkg/controller/datavolume-controller.go:852\nkubevirt.io/containerized-data-importer/pkg/controller.(*DatavolumeReconciler).reconcileSmartClonePvc\n\tpkg/controller/datavolume-controller.go:791\nkubevirt.io/containerized-data-importer/pkg/controller.(*DatavolumeReconciler).Reconcile\n\tpkg/controller/datavolume-controller.go:415\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99\nruntime.goexit\n\tGOROOT/src/runtime/asm_amd64.s:1371","stacktrace":"kubevirt.io/containerized-data-importer/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tvendor/github.com/go-logr/zapr/zapr.go:132\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:302\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99"}
```

I delete the controller pod to refresh token, and cloning successed. 

By the way, the components of cdi has been deployed for a month, but  I'm not sure when the token expired.
```
[root@cloud-3 ~]# kubectl get po -ncdi
NAME                               READY   STATUS    RESTARTS   AGE
cdi-apiserver-95ff4d94f-rm422      1/1     Running   0          30d
cdi-deployment-547bc54fcf-lmwht    1/1     Running   0          3h18m
cdi-operator-65cd8499b9-xvgkv      1/1     Running   10         30d
cdi-uploadproxy-6bb4cbcf5c-gtj5r   1/1     Running   0          30d
```

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.41.1
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration: 
- Install tools: kubeadm
- Others:

**Comment by awels** [comment]
We rotate certificates on a daily basis, so they should not be expired. Does your storage class support CSI snapshotting? Or does it advertise it does and then doesn't actually support it? Also what is the provisioner for your storage class, it could be that you have an empty storage profile causing the cloning to fail.

**Comment by tiezhuoyu** [comment]
>

**Comment by tiezhuoyu** [comment]
> We rotate certificates on a daily basis, so they should not be expired. Does your storage class support CSI snapshotting? Or does it advertise it does and then doesn't actually support it? Also what is the provisioner for your storage class, it could be that you have an empty storage profile causing the cloning to fail.

We use ceph-csi and it support snapshotting. Manually creating snapshots works fine.
The storageclass is as follows:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-rbd-nbd
mountOptions:
- discard
parameters:
  clusterID: 1bac3fb0-2f31-45ce-9d9e-b12a044992b5
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  imageFeatures: layering
  mounter: rbd-nbd
  pool: ceph-ssd-pool-1
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The provisioner is 'rbd.csi.ceph.com'.
