### ISSUE TITLE
why cdi-importer needs to consume so much memory？

### ISSUE THREAD

**Issue by iswbm** [kubevirt/containerized-data-importer#2110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

I wanted to use cdi to create a virtual machine, and the cdi pod OOM failed,
```bash
[root@master01 ~]# kubectl get po 
NAME                               READY   STATUS      RESTARTS   AGE
importer-wbm-test--fs-top-old-vda          0/1     OOMKilled   1          76s
```

I had to modify the cdi configuration to make it successful.
```bash
kubectl patch cdi cdi --patch '{"spec": {"config": {"podResourceRequirements": {"limits": {"memory": "5G"}}}}}' --type merge
```

I used kubectl top to check the resource usage and found that cdi consumes up to 4G of memory
![image](https://user-images.githubusercontent.com/22311419/149879934-b0c590a4-7ba1-489b-a28d-fc4001baca39.png)

What I'm wondering is why it needs to consume so much memory.

**What you expected to happen**:

cdi-import can work with less memory usage

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

datavolume datavolume spec:

```
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      limits:
        storage: 20Gi
      requests:
        storage: 20Gi
    storageClassName: xxx
    volumeMode: Block
  source:
    http:
      url: http://xxx
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.43.0
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration:
- Install tools: 
- Others:

**Comment by mhenriks** [comment]
Hi @iswbm can you tell us a little more about the target image?  What is the size and format (qcow/raw) and is it compressed?

**Comment by iswbm** [comment]
> Hi @iswbm can you tell us a little more about the target image? What is the size and format (qcow/raw) and is it compressed?

Hi， @mhenriks 

The image I use is  qcow2 format, 800M， and it has been compressed.

the problem was solved when I changed the parameters of qemu-img from writeback to directsync, I guess it was the cache problem.

**Comment by mhenriks** [comment]
Hi @iswbm what compression was used?  Gzip?  xz?  qcow build in compression?

**Comment by adiroiban** [comment]
I got a similar issue

```
$ virtctl image-upload pvc iso-win-2019 --access-mode=ReadWriteOnce --size=8G --uploadproxy-url=https://palmita:32001 --force-bind --insecure --wait-secs=60 --image-path ~/Downloads/SW_DVD9_Win_Server_STD_CORE_2019_1909.4_64Bit_English_DC_STD_MLF_X22-29333.ISO 
PVC default/iso-win-2019 not found 
PersistentVolumeClaim default/iso-win-2019 created
Waiting for PVC iso-win-2019 upload pod to be ready...
Pod now ready
Uploading data to https://palmita:32001

 563.06 MiB / 5.01 GiB [==============>----------------------------------------------------------------------------------------------------------------------]  10.98% 17s

unexpected return value 502,
```


The pod logs

```
I1103 13:51:58.607965       1 importer.go:103] Starting importer
I1103 13:51:58.608000       1 importer.go:172] begin import process
I1103 13:51:58.756808       1 data-processor.go:356] Calculating available size
I1103 13:51:58.756854       1 data-processor.go:368] Checking out file system volume size.
I1103 13:51:58.756872       1 data-processor.go:376] Request image size not empty.
I1103 13:51:58.756892       1 data-processor.go:381] Target size 8G.
I1103 13:51:58.756932       1 data-processor.go:255] New phase: TransferDataFile
I1103 13:51:58.844048       1 util.go:194] Writing data...
I1103 13:51:59.844186       1 prometheus.go:75] 1.23
I1103 13:52:00.844259       1 prometheus.go:75] 2.45
I1103 13:52:01.844548       1 prometheus.go:75] 3.71
I1103 13:52:02.844622       1 prometheus.go:75] 4.87
I1103 13:52:03.844683       1 prometheus.go:75] 6.11
I1103 13:52:04.844778       1 prometheus.go:75] 7.32
I1103 13:52:05.844901       1 prometheus.go:75] 8.60
I1103 13:52:06.844978       1 prometheus.go:75] 9.89
```


---------

I get a similar issue if I try without cli

```yaml

apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "win-2019-iso"
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    http:
      url: "https://local.dev/minio/iso/windows/SW_DVD9_Win_Server_STD_CORE_2019_1909.4_64Bit_English_DC_STD_MLF_X22-29333.ISO"
  pvc:
    storageClassName: local-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "8G"
```


the POD status

```
 containerStatuses:
    - name: importer
      state:
        waiting:
          reason: CrashLoopBackOff
          message: back-off 2m40s restarting failed container=importer
            pod=importer-win-2019-iso_default(ced75f7a-d012-44ae-81a4-ef65366b66fc)
      lastState:
        terminated:
          exitCode: 137
          reason: OOMKilled
          startedAt: 2023-11-03T13:54:32Z
          finishedAt: 2023-11-03T13:54:41Z
          containerID: containerd://9b39c9dee046e291959ead4537e41e763b6c90c03aa7f8bb3ae136e6bdf6f5cf
      ready: false
      restartCount: 5
      image: quay.io/kubevirt/cdi-importer:v1.57.0
      imageID: quay.io/kubevirt/cdi-importer@sha256:3143bbc67cdc6267eb48b7eaac664b8551ac4c11401dfbf4921efd3f233e6ce9
      containerID: containerd://9b39c9dee046e291959ead4537e41e763b6c90c03aa7f8bb3ae136e6bdf6f5cf
      started: false
  qosClass: Burstable
```

**Comment by ydcool** [comment]
same issue  here.
/reopen

**Comment by NeverTeaser** [comment]
same issue here.
DataVolume define 
``` yaml 
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "ubuntu"
spec:
  storage:
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/bionic/20230607/bionic-server-cloudimg-amd64-root.tar.xz"
```
when i watch the datavolumes, the terminal info 
``` sh
kubectl get datavolumes  -w 

ubuntu   ImportInProgress   33.38%                28s
ubuntu   ImportInProgress   38.01%                30s
ubuntu   ImportInProgress   42.42%                32s
ubuntu   ImportInProgress   46.55%                34s
ubuntu   ImportInProgress   50.82%                36s
ubuntu   ImportInProgress   55.40%                38s
ubuntu   ImportInProgress   60.19%                40s
ubuntu   ImportInProgress   64.79%                42s
ubuntu   ImportInProgress   64.79%                43s
ubuntu   ImportInProgress   64.79%     1          44s
ubuntu   ImportInProgress   4.44%      1          46s
ubuntu   ImportInProgress   8.33%      1          48s
ubuntu   ImportInProgress   11.34%     1          50s
ubuntu   ImportInProgress   15.55%     1          52s
```
always restart to import the image

describe import-xxx pod  info 
```
 importer:
    Container ID:    docker://79e6dc41b90bd86e59f3f481219eae8b53885146cb630b586e35ca0d805145bb
    Image:           quay.io/kubevirt/cdi-importer:v1.58.0
    Image ID:        docker-pullable://quay.io/kubevirt/cdi-importer@sha256:72ee3dd7073a8c25c016f29d2075afe220a607e6081c50f48b0b0a16ddb516f6
    Port:            8443/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      -v=1
    State:          Running
      Started:      Fri, 29 Dec 2023 15:53:04 +0800
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 29 Dec 2023 15:52:19 +0800
      Finished:     Fri, 29 Dec 2023 15:52:50 +0800
    Ready:          True
    Restart Count:  2
    Limits:
      cpu:     750m
      memory:  600M
    Requests:
      cpu:     100m
      memory:  60M
```

And i patch the  cdi  `podResourceRequirements` then import  success 

`kubectl patch cdi cdi --patch '{"spec": {"config": {"podResourceRequirements": {"limits": {"memory": "1G"}}}}}' --type merge
`
