### ISSUE TITLE
Travis - Automate a release email to mailing list

### ISSUE THREAD

**Issue by copejon** [kubevirt/containerized-data-importer#217]
Whenever a new release is published, announce the release to the team's mailing list automatically via travis-ci.

**Comment by copejon** [comment]
Travis-CI does not support notifications on specific event.  It's either all or nothing, which requires configuration on the mailing-list side to filter out spammy CI notifications.

**Comment by rmohr** [comment]
You can use a custom deploy step and use the same conditions like you use for creating a github release inside travis:

```
- provider: script
  script: bash scripts/send-email.sh
  branches:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
  on:
    tags: true
    repo: kubevirt/containerized-data-importer
```
