### ISSUE TITLE
TransferRunning condition message should be updated with current progress.

### ISSUE THREAD

**Issue by kaovilai** [kubevirt/containerized-data-importer#2234]
Current
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
status:
  conditions:
    - lastHeartbeatTime: '2022-04-11T18:03:00Z'
      lastTransitionTime: '2022-04-11T18:03:00Z'
      message: PVC centos9-dv Bound
      reason: Bound
      status: 'True'
      type: Bound
    - lastHeartbeatTime: '2022-04-11T18:06:08Z'
      lastTransitionTime: '2022-04-11T18:02:54Z'
      reason: TransferRunning
      status: 'False'
      type: Ready
    - lastHeartbeatTime: '2022-04-11T18:03:18Z'
      lastTransitionTime: '2022-04-11T18:03:18Z'
      reason: Pod is running
      status: 'True'
      type: Running
  phase: ImportInProgress
  progress: 67.60%
```

Proposed
```diff,yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
status:
  conditions:
    - lastHeartbeatTime: '2022-04-11T18:03:00Z'
      lastTransitionTime: '2022-04-11T18:03:00Z'
      message: PVC centos9-dv Bound
      reason: Bound
      status: 'True'
      type: Bound
    - lastHeartbeatTime: '2022-04-11T18:06:08Z'
      lastTransitionTime: '2022-04-11T18:02:54Z'
+      message: "ImportInProgress 67.60%"
      reason: TransferRunning
      status: 'False'
      type: Ready
    - lastHeartbeatTime: '2022-04-11T18:03:18Z'
      lastTransitionTime: '2022-04-11T18:03:18Z'
      reason: Pod is running
      status: 'True'
      type: Running
  phase: ImportInProgress
  progress: 67.60%
```

Motivation: OpenShift Web Console do not natively show current progress. YAML view is not refreshed automatically.
![image](https://user-images.githubusercontent.com/11228024/162803079-77d29977-f9b0-4013-ac19-118a547e17c5.png)

Current workaround: `watchi kubectl get dv`
