### ISSUE TITLE
Does the storageclass have the annotation which can override global filesystemOverhead?

### ISSUE THREAD

**Issue by ZhangShuaiyi** [kubevirt/containerized-data-importer#2312]
Refer to [CDI Configuration](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md), configure cdi/cdi like this can set filesystemOverhead of storageClass local-path.
```
spec:
  config:
    filesystemOverhead:
      global: "0.055"
      storageClass:
        local-path: "0.0"
```
Does the storageclass have the annotation like "cdi.kubevirt.io/clone-strategy", which can be configured on storageClass to override global filesystemOverhead.
