### ISSUE TITLE
URL that is pass to nbdkit includes the username/password and it should not

### ISSUE THREAD

**Issue by k8scoder192** [kubevirt/containerized-data-importer#2338]
**What happened**:
URL that is pass to nbdkit includes the username/password. 

See snippet below showing how the secret username and pass are included in the URL
```
nbdkit --foreground --readonly --exit-with-parent -U /var/run/nbdkit.sock --pidfile/var/run/nbdkit.pid -r curl url=https://<MY USERNAME>:<MY PASSWD>@localhost:8081/my-repository/my_vm_image.qcow2
```

**What you expected to happen**:
Shouldn't send username and password as part of the URL. 
Per https://pkg.go.dev/net/url#UserPassword, [RFC 2396](https://rfc-editor.org/rfc/rfc2396.html) warns that interpreting Userinfo this way “is NOT RECOMMENDED

**Basic authentication should be done via**
```
curl -u $USER:$PASS -O https://<path to file >
which yields a HEADER with  'Authorization: Basic .....'
```

**How to reproduce it (as minimally and precisely as possible)**:
**Create and apply Secrets yaml**
```
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-secret
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: "<redacted>"
  secretKey:    "<redacted>"
```

**Create and apply DV**
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: artifactory-dv
spec:
  source:
      http:
         url: "http://localhost:8081/my-repository/my_vm_image.qcow2"
         secretRef: endpoint-secret 
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```

**You will get error message with 401**
```
   message: "Unable to connect to http data source: expected status code 200, got
      401. Status: 401  kubevirt.io/containerized-data-importer/pkg/importer.createHTTPReader
      \tpkg/importer/http-datasource.go:338 kubevirt.io/containerized-data-importer/pkg/importer.NewHTTPDataSource
      \tpkg/importer/http-datasource.go:99 main.newDataSource \tcmd/cdi-importer/importer.go:234
      main.handleImport \tcmd/cdi-importer/importer.go:152 main.main \tcmd/cdi-importer/importer.go:122
      runtime.main \tGOROOT/src/runtime/proc.go:255 runtime.goexit \tGOROOT/src/runtime/asm_amd64.s:1581"
    reason: Error
```

**Additional context**:

**Environment**:
**Component versions**
[operator.cdi.kubevirt.io/createVersion=v1.49.0](http://operator.cdi.kubevirt.io/createVersion=v1.49.0)
[controller-gen.kubebuilder.io/version](http://controller-gen.kubebuilder.io/version): v0.7.0
[k8s.gcr.io/sig-storage/csi-attacher:v3.4.0](http://k8s.gcr.io/sig-storage/csi-attacher:v3.4.0)
[k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0](http://k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0)
[k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0](http://k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0)
[k8s.gcr.io/sig-storage/csi-resizer:v1.4.0](http://k8s.gcr.io/sig-storage/csi-resizer:v1.4.0)
[k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1](http://k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1)
[quay.io/cephcsi/cephcsi:v3.6.1](http://quay.io/cephcsi/cephcsi:v3.6.1)
virt-operator:v0.53.1

- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
