### ISSUE TITLE
HTTP import Ubuntu Server image to DataVolume is extremely slow

### ISSUE THREAD

**Issue by pcgeek86** [kubevirt/containerized-data-importer#2358]
**What happened**:

Using the CDI to import from a disk image, hosted on an HTTP endpoint, is extremely slow.

**What you expected to happen**:

Importing a disk image is fast.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  namespace: default
  name: ubuntu-jammy2
spec:
  source:
      http:
         url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
```

**Additional context**:

It's only 32% completed after 21 minutes.

```
PS /home/ubuntu> sudo kubectl get dv
NAME            PHASE              PROGRESS   RESTARTS   AGE
ubuntu-jammy                                             37m
ubuntu-jammy2   ImportInProgress   32.14%                21m
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.51.0
- Kubernetes version (use `kubectl version`): K3S 1.23.8
- DV specification: N/A
- Cloud provider or hardware configuration: AWS `c5.metal` instance type
- OS (e.g. from /etc/os-release): Ubuntu Server 22.04 LTS Jammy Jellyfish
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

Related to #2058

**Comment by pcgeek86** [comment]
@awels Hello, thank you for responding. I did link this issue to #2058, because I was unable to re-open it. 

I use SpaceX Starlink satellite internet at home, and I am able to download the Ubuntu 22.04 LTS cloud image at ~10 MB/sec. Hence, I am reasonably confident that running the same process on a bare metal AWS cloud server should yield much better performance.

Here's the download going in Chrome, to my local developer workstation:

![image](https://user-images.githubusercontent.com/466713/178817431-ae3f7e2d-9de8-4bcd-a325-8eb7647b6ddd.png)

I'm not inclined to believe that the Canonical Ubuntu cloud image server is necessarily the root cause of this problem.

**Comment by mhenriks** [comment]
@pcgeek86 @awels 

It appears that "qemu-img convert" is the culprit here.  On my system:

`wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img` took 40s

`qemu-img convert  -p -O raw https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img disk.img` took 10 minutes

This is because `qemu-img convert` does a bunch of small range requests rather than streaming the entire file in one go.

Also, assuming our content type detection is working correctly, it is completely unnecessary to run `qemu-img convert`

**Comment by mhenriks** [comment]
Ah, it appears that the file is qcow2, so conversion is necessary.  I assumed by ".img" extension that it was raw

Looks like now we get into the tradeoff where it is probably faster to download the file to scratch before doing conversion.  Maybe we should discuss making this configurable

**Comment by mattmadeofpasta** [comment]
/remove-lifecycle stale

- The issue is still present and I was able reproduce with `v1.55.0`.

- Debian is also affected:
  https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2

- Workaround:

  In some special cases, the CDI importer does not go through the `nbkit` `curl` plugin, but
  instead first downloads the file to a scratch space. See 
  https://github.com/kubevirt/containerized-data-importer/blob/main/doc/scratch-space.md
  
  One of the cases is when the server of the source URL uses a custom certificate authority(CA). We
  can force the scratch space method by providing an empty custom CA. The importer should pick up
  the OS cert store, append our empty CA, and helpfully not complain that the custom CA an is an
  empty string. I haven't verified it, but in theory the importer should still validate the
  certificate of the server with the OS cert store.

  This workaround is risky. It relies on internal implementation details and the behavior could
  change between patch versions. 

  ```yaml
  apiVersion: cdi.kubevirt.io/v1beta1
  kind: DataVolume
  metadata:
    name: ubuntu-jammy
  spec:
    source:
      http:
        # certConfigMap with an empty cert is to work around this issue:
        # https://github.com/kubevirt/containerized-data-importer/issues/2358
        certConfigMap: empty-cert
        url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    pvc:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  ---
  apiVersion: cdi.kubevirt.io/v1beta1
  kind: DataVolume
  metadata:
    name: debian-11
  spec:
    source:
      http:
        # certConfigMap with an empty cert is to work around this issue:
        # https://github.com/kubevirt/containerized-data-importer/issues/2358
        certConfigMap: empty-cert
        url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
    pvc:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  ---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: empty-cert
  data:
    ca.pem: ""
  ```
