### ISSUE TITLE
Feature Request: Support retained PV as source

### ISSUE THREAD

**Issue by haslersn** [kubevirt/containerized-data-importer#2359]
**Is your feature request related to a problem? Please describe**:

I accidentally deleted a DataVolume. The PersistentVolume was still there. I wanted to reuse it, including its content. However, containerized-data-importer currently doesn't support this.

**Describe the solution you'd like**:

Perhaps something like the following could be made to work. To date, this doesn't work, because the importer would create a blank disk inside the volume, AFAIK.

```
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: <PV to reclaim>
```

**Describe alternatives you've considered**:

I think a workaround is to manually create a PVC to reclaim the PV and then use the PVC source. However, this would create a copy of the data.
