### ISSUE TITLE
Container disks imported to block volumes have incorrect permissions

### ISSUE THREAD

**Issue by darkmuggle** [kubevirt/containerized-data-importer#2378]
**What happened**:
When importing a containerized disk via a data volume definition to a block CSI driver (e.g. Longhorn, ISCSI) the resultant disk has the wrong permissions. When importing to a file driver such as NFS, it imports with the correct permissions. 

**What you expected to happen**:
- Imports correctly with the correct permissions

**How to reproduce it (as minimally and precisely as possible)**:
- Import a containerized disk onto a block CSI driver
- Works fine on files drivers (e.g NFS)

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 20220727_59a34eaa-arm64
- Kubernetes version (use `kubectl version`): 1.23.4+k3s1
- DV specification: 
- Cloud provider or hardware configuration: Bare Metal ARM64
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4
- Kernel (e.g. `uname -a`): 5.15.0-41-generic

The Container disk dockerfile looks like:
```
FROM registry.fedoraproject.org/fedora:36 AS utils

ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ARCH=amd64; else ARCH=arm64; fi && \
    mkdir /disk && \
    curl -Ls -o /disk/disk.img "https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-${ARCH}.img" && \
    ls -lf /disk/*

RUN dnf -y install qemu-img dumb-init bash
RUN qemu-img resize /disk/disk.img +40G
RUN chmod 0666 /disk/disk.img

FROM scratch
LABEL distro=ubuntu
LABEL distro.version=20.04
COPY --from=0 /disk/disk.img /disk/
```

KubeVirt 0.55 shows the following error when attempting to start the VM:
```
Could not open '/var/run/kubevirt-private/vmi-disks/root-disk/disk.img': Permission denied')","timestamp":"2022-07-28T21:16:35.171734Z","uid":"68daec74-05dd-4a2c-8b9d-805d8c0663ca"}
```

Breaking into the virt-launcher pod, you can see:
```
bash-4.4# stat /var/run/kubevirt-private/vmi-disks/root-disk/disk.img
  File: /var/run/kubevirt-private/vmi-disks/root-disk/disk.img
  Size: 60880322560	Blocks: 2750056    IO Block: 4096   regular file
Device: 10314h/66324d	Inode: 11          Links: 1
Access: (0660/-rw-rw----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-07-28 21:14:18.991954395 +0000
Modify: 2022-07-28 21:14:19.007954364 +0000
Change: 2022-07-28 21:14:41.947910216 +0000
 Birth: 2022-07-28 21:13:07.676091642 +0000
```

**Comment by darkmuggle** [comment]
Taking a look at the same container disk imported to an NFS:
```
bash-4.4# stat root-disk/
  File: root-disk/
  Size: 3         	Blocks: 2          IO Block: 131072 directory
Device: 200077h/2097271d	Inode: 7513985     Links: 2
Access: (2777/drwxrwsrwx)  Uid: (65534/ UNKNOWN)   Gid: (  107/    qemu)
Access: 2022-07-28 23:01:16.262112736 +0000
Modify: 2022-07-28 23:01:53.647707859 +0000
Change: 2022-07-28 23:01:53.647707859 +0000
 Birth: -
```

I suspect that the 2777 (yikes!) octal permissions is the result of the NFS appliance setting the ACL's. However, you'll notice that on the block-backed disk its own by `root` and on the NFS backed its `qemu`.

**Comment by awels** [comment]
So I am a little confused as to what you are talking about. If you use a raw block device (volumeMode: block) there is no disk.img file, we write the bytes directly to the block device. So this suggestes to me you imported to a filesystem volume backed by iSCSI or longhorn? I would still like to see your VM definition and the datavolume one so I can better understand the scenario you are talking about. CDI uses fsGroups to ensure that imported disk images are at least in the kvm group so that kubevirt can read it.

**Comment by darkmuggle** [comment]
Here's the definition I'm using. 

The CSI block driver in question setups a filesystem and mounts it, so it is on a file system. To clear up the confusion, the block is not a raw block volume. 

```
apiVersion: v1
kind: KubeVirt
metadata:
  annotations:
    smbios.vm.kubevirt.io/baseBoardManufacturer: Artisanal and Orgranic Virtual Machines
  creationTimestamp: null
  name: bhoward-1659111470
  namespace: virts
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: dv-bhoward-1659111470-root-1659111470
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: block-csi
      source:
        registry:
          secretRef: kubevirt-quay-secrets
          url: <REDACTED>
  runStrategy: Manual
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      creationTimestamp: null
     spec:
      dnsPolicy: ClusterFirst
      domain:
        chassis:
          asset: 543029708-bhoward
          manufacturer: DDN Devops
          serial: "1659111470"
          sku: server-arm64
          version: 2022-07-28.bd647b0
        cpu:
          cores: 8
          model: host-passthrough
          sockets: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: scsi
            name: root-disk
            serial: root-543029708-1
          - disk:
              bus: virtio
            name: cloudinitdisk
            serial: cidata-543029708-2
          interfaces:
          - bridge: {}
            name: default
          - name: sriov-net-1
            sriov: {}
          rng: {}
        firmware:
          serial: "1659111470"
        machine:
          type: virt
        memory:
          guest: 20Gi
          hugepages:
            pageSize: 2Mi
        resources:
          limits:
            cpu: "8"
            memory: 21Gi
          requests:
            cpu: "8"
            memory: 21Gi
      hostname: bhoward-1659111470
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: default/sriov-net
        name: sriov-net-1
      priorityClassName: system-cluster-critical
      subdomain: vms
      volumes:
      - dataVolume:
          name: dv-bhoward-1659111470-root-1659111470
        name: root-disk
      - cloudInitNoCloud:
          secretRef:
            name: vm-cloudinit-bhoward-1659111470
        name: cloudinitdisk
      - containerDisk:
          image: quay.io/red/kubernetes:empty-disk-128G
          imagePullSecret: red-swarm-pull-secret
        name: dv-bhoward-1659111470-1-1659111470
      - containerDisk:
          image: <REDACTED>
          imagePullSecret: red-swarm-pull-secret
        name: dv-bhoward-1659111470-2-1659111470
      - containerDisk:
          image: <REDACTED>
          imagePullSecret: red-swarm-pull-secret
        name: dv-bhoward-1659111470-3-1659111470
```

And the DV definition:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  creationTimestamp: "2022-07-29T16:27:51Z"
  generation: 7
  labels:
    kubevirt.io/created-by: bb017744-aa46-4509-95fb-a66b050354e9
  name: dv-bhoward-1659112070-root-1659112071
  namespace: virts
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: bhoward-1659112070
    uid: bb017744-aa46-4509-95fb-a66b050354e9
  resourceVersion: "440666"
  uid: 5fe1036e-d7ed-44f9-980d-7fc452a2b0f2
spec:
  priorityClassName: system-cluster-critical
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 60Gi
    storageClassName: block-csi
  source:
    registry:
      secretRef: kubevirt-quay-secrets
      url: <REDACTED
status:
  claimName: dv-bhoward-1659112070-root-1659112071
  conditions:
  - lastHeartbeatTime: "2022-07-29T16:27:53Z"
    lastTransitionTime: "2022-07-29T16:27:53Z"
    message: PVC dv-bhoward-1659112070-root-1659112071 Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2022-07-29T16:28:03Z"
    lastTransitionTime: "2022-07-29T16:27:51Z"
    reason: TransferRunning
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2022-07-29T16:28:03Z"
    lastTransitionTime: "2022-07-29T16:28:03Z"
    reason: Pod is running
    status: "True"
    type: Running
  phase: ImportInProgress
  progress: N/A
```
