### ISSUE TITLE
Allow use of imagePullSecrets on CDI operator, infra and workload pods

### ISSUE THREAD

**Issue by shannonmitchell** [kubevirt/containerized-data-importer#2395]
**Is your feature request related to a problem? Please describe**:

We are using kubevirt and cdi in a security environment that has only private registries and limited to no internet access.  We are also limited on access to the kubernetes nodes, so the registry secrets can't be set up globally.  This requires kubernetes imagePullSecrets to be used for both deployments and automated testing. Kubevirt allows for the setting of customizeComponents for dynamic infra/workload pods spun up by the operator.  Kubevirt also supports imagePullSecrets direction in the virt-operator spec.  CDI is currently missing the ability to do the same.

**Describe the solution you'd like**:

A similar solution to specify imagePullSecrets that KubeVirt has should work.  See the customizeComponents and operator spec info from above.  Hard coding imagePullSecrets similar to how you guys are doing the imagePullPolicy should work as well.

**Describe alternatives you've considered**:

We are currently using opa gatekeeper mutations to inject the imagePullSecrets into the CDI serviceaccounts, but a solution done through the CDI configs would be preferred.  

**Additional context**:

Supporting imagePullSecrets should help with the adoption of CDI into more secure Enterprise spaces.

**Comment by awels** [comment]
Thanks for the report @mhenriks any thoughts on this? Seems the KubeVirt thing that allows this is https://github.com/kubevirt/kubevirt/pull/3612 and https://github.com/kubevirt/kubevirt/pull/5563

**Comment by mhenriks** [comment]
> Thanks for the report @mhenriks any thoughts on this? Seems the KubeVirt thing that allows this is [kubevirt/kubevirt#3612](https://github.com/kubevirt/kubevirt/pull/3612) and [kubevirt/kubevirt#5563](https://github.com/kubevirt/kubevirt/pull/5563)

Thanks for the request @shannonmitchell, CDI should definitely support this.

**Comment by ninjacoder80** [comment]
Hi @awels and @mhenriks any progress on this? 

Looks like Kubevirt added support for this https://github.com/kubevirt/kubevirt/pull/5563

**Comment by barhoumikhaled** [comment]
@shannonmitchell do you have examples please on how to `opa gatekeeper mutations to inject the imagePullSecrets into the CDI serviceaccounts`?
I tried below mutation, but it did not inject the imagepullsecrets to the SA
```
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: image-pull-secret
  namespace: cdi
spec:
  applyTo:
  - groups: [""]
    kinds: ["ServiceAccount"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["ServiceAccount"]
    namespaces: ["cdi"]
  location: "imagePullSecrets"
  parameters:
    assign:
      value:
        - name: pull-secret
```

**Comment by shannonmitchell** [comment]
The following worked for me.  I added the 'inject-sa-imgpullsec: true' label to the namespace being used for the match. Make sure to enable mutations in the gatekeeper configs as it is disabled by default. The secrets used have to exist in that namespace as well. 
```
apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: sa-image-pull-secrets
spec:
  applyTo:
    - groups: [""]
      kinds: ["ServiceAccount"]
      versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: ["*"]
        kinds: ["ServiceAccount"]
    namespaceSelector:
      matchLabels:
        inject-sa-imgpullsec: "true"
  location: "imagePullSecrets"
  parameters:
    assign:
      value:
        - name: private-registry
        - name: repo1-read-creds
```
