### ISSUE TITLE
The controller removes the DV if it's created as a "blank"

### ISSUE THREAD

**Issue by farcaller** [kubevirt/containerized-data-importer#2442]
**What happened**:
The controller creates a PVC and removes the DV if the source is `blank: {}`.

**What you expected to happen**:
The controller doesn't touch my DVs.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl create -f - <<EOF
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: test
  finalizers:
  - kubernetes
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: zfspv-block
    volumeMode: Block
  source:
    blank: {}
EOF
```

After the PVC is created the DV gets `metadata.deletionTimestamp`, meaning it's gone (it will actually be gone if the finalizers are missing).

**Additional context**:
While working with kubevirt we sometimes need to perform the restore manually, thus needing the use of a blank DV. Given we create those from ArgoCD, the CD gets very confused about them being deleted. I don't see a reason why CDI would want to maintain a lifecycle of objects it doesn't own.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.55.0
- Kubernetes version (use `kubectl version`): 1.24
- DV specification: See above
