### ISSUE TITLE
What can be created with permissions for datavolumes/source

### ISSUE THREAD

**Issue by sergeimonakhov** [kubevirt/containerized-data-importer#2457]
**Description**:
All documents indicate whether the rights to datavolumes/source should be granted:
```yaml
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["create"]
```
but nowhere is it described what can be created using these rights, pod/snapshots/etc?

**What you expected**:
Description of what can be created using these rights

**URL**:
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/RBAC.md#pvc-cloning
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/efficient-cloning.md#prerequisites
