### ISSUE TITLE
release v1.1.0-alpha1 uses v1.0.0 importer pod

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#252]
importer pod v1.0.0 is hard coded as the default unless an ENV VAR is set to specify a different one. Our latest CDI release does not set that ENV VAR which means we have a v1.1.0-alpha.1 version using the old v1.0.0 importer pod. 

example manifest.  ENV VARs need to be set in this manifest reflecting the importer pod version the controller should use. 
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cdi-deployment
  namespace: default  # update accordingly based on the namespace you are deploying in
  labels:
    cdi.kubevirt.io: ""
    app: containerized-data-importer
spec:
  selector:
    matchLabels:
      app: containerized-data-importer
  replicas: 1
  template:
    metadata:
      labels:
        app: containerized-data-importer
    spec:
      serviceAccountName: cdi-sa
      containers:
      - name: cdi-controller
        image: kubevirt/cdi-controller:v1.1.0-alpha.1
        imagePullPolicy: IfNotPresent
        args: ["-v=1"] # default verbosity; change to 2 or 3 for more detailed logging
---
```
