### ISSUE TITLE
High availability

### ISSUE THREAD

**Issue by kvaps** [kubevirt/containerized-data-importer#2560]
**Is your feature request related to a problem? Please describe**:

Currently CDI has hardcoded amount of replicas equals to 1:

https://github.com/kubevirt/containerized-data-importer/blob/00bc43f35b69a0c84a5128de716c7feffe6ae07d/pkg/operator/resources/namespaced/controller.go#L166

https://github.com/kubevirt/containerized-data-importer/blob/00bc43f35b69a0c84a5128de716c7feffe6ae07d/pkg/operator/resources/namespaced/apiserver.go#L96

https://github.com/kubevirt/containerized-data-importer/blob/00bc43f35b69a0c84a5128de716c7feffe6ae07d/pkg/operator/resources/namespaced/uploadproxy.go#L89

I would like to run CDI deployments in 2 replicas

**Describe the solution you'd like**:

Ability to specify amount of replicas for CDI deployments, same as for KubeVirt:

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  infra:
    replicas: 2
```

**Describe alternatives you've considered**:

**Additional context**:
