### ISSUE TITLE
Add ability to set cdi-uploadserver-client-cert certificate renewal period

### ISSUE THREAD

**Issue by vriabyk** [kubevirt/containerized-data-importer#2755]
**Is your feature request related to a problem? Please describe**:
We deploy containerized-data-importer along with kubevirt in our k8s clusters. By default both applications generate internal certificates for 24hours. In our case it isn't critical to renew certificates so often and we decided to increase it via certConfig option, for example:
```
        certConfig:
          ca:
            duration: 87660h
            renewBefore: 86940h
          server:
            duration: 87660h
            renewBefore: 86940h
 ```
This works fine for `cdi-apiserver-server-cert` and `cdi-uploadproxy-server-cert`, but not for `cdi-uploadserver-client-cert`. Please correct me if I am wrong, but the time [is hardcoded here](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/operator/resources/cert/factory.go#L120). There is no `Configurable: true` for this certificate, that's why the setting isn't working for it. Am I missing something?

**Describe the solution you'd like**:
I would like to be able to set duration and renewBefore options for this certificate as well. Probably it will be enough just to add `Configurable: true` in the code.
