### ISSUE TITLE
Pod doesn't start when DataVolume includes secretRef to AWS

### ISSUE THREAD

**Issue by KastenMike** [kubevirt/containerized-data-importer#2819]
**What happened**:
CDI fails to read the AWS secret keys correctly and assign them to the importer pod meaning the import never happens.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-sec
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: "access key val"
  secretKey: "secret key val" 
```

The values are used frequently ok outside of CDI and come directly from IAM. Then a DV definition to make use of it:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "extra-drive"
spec:
  source:
      http:
         url: "https://s3.us-west-1.amazonaws.com/bucket/folder/some-file.iso" # S3 or GCS
         secretRef: "aws-sec"  # Optional
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "2Gi"
    storageClassName: ocs-storagecluster-cephfs
```

Check pod definition for issues:

`kubectl describe pod importer-extra-drive`

Some highlights:
```
IMPORTER_ACCESS_KEY_ID:        <set to the key 'accessKeyId' in secret 'aws-sec'>  Optional: false
IMPORTER_SECRET_KEY:           <set to the key 'secretKey' in secret 'aws-sec'>    Optional: false

State:          Waiting
      Reason:       CreateContainerError
    Ready:          False

Error: container create failed: time="2023-07-26T15:36:48Z" level=error msg="runc create failed: unable to start container process: error during container init: environment variable value can't contain null(\\x00): \"IMPORTER_ACCESS_KEY_ID=\\x00�\\x00A\\x11\\x00(҃\\x00d�1\\x11�\""
```

The errors above are with the standard AWS key & secret you get from IAM which are already base64 characters. If I try `openssl base64 -e <<<aws key` and use these values in the secret then I get:
```
State:          Terminated
      Reason:       Error
      Message:      Unable to connect to http data source: expected status code 200, got 400. Status: 400 Bad Request
```

**Additional context**:
Is I make the file public and remove the `secretRef` then it loads ok but that's not ideal

**Environment**:
- CDI version: There doesn't seem to be a way to tell from `kubectl -nopenshift-cnv get deployment cdi-deployment -oyaml` but it's OCP `4.13.2` although I had the same issue with the previous version also.
- Kubernetes version (use `kubectl version`): v1.26.3
- Cloud provider or hardware configuration: AWS `c5n.metal`

**Comment by awels** [comment]
Any particular reason you can't use the s3 source instead of http? something like this:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "extra-drive"
spec:
  source:
      s3:
         url: "https://s3.us-west-1.amazonaws.com/bucket/folder/some-file.iso" # S3 or GCS
         secretRef: "aws-sec"  # Optional
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "2Gi"
    storageClassName: ocs-storagecluster-cephfs
```
Also I would not use cephfs for the storage class, there are some subtle issues with cephfs. It will work but you will get a bunch of alerts about the volume being full even though it is not.

If the accessKeyId and secretKey values you get are already base64 encoded, you should be able to just paste them as the values, and it should work.
