### ISSUE TITLE
DV smart clone stucked when pod using the old PVC.

### ISSUE THREAD

**Issue by a180285** [kubevirt/containerized-data-importer#2829]
**What happened**:
I want to take a snaphot of one disk in my running vm. So I use following yaml.
The clone process stucked, and saying `pod default/virt-launcher-abcd-lnvg9 using PersistentVolumeClaim rbd-7tsdhrswuug6`

But actually, 
* the source PVC is RWX
* And the storageClassName: ecs-rbd-sc, actually support smart clone, snapshot clone.

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rbd-img-q9i6mvylu0fc
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 100Gi
    storageClassName: ecs-rbd-sc
    volumeMode: Block
  source:
    pvc:
      name: rbd-7tsdhrswuug6
      namespace: default
```

**What you expected to happen**:
The DV can successfully create a new PVC as a snapshot for source PVC. When the VM is running.

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:
`storageClassName: ecs-rbd-sc` is based on ceph rbd csi plugin. which support snapshot feature.
My CDI code is using branch release-v1.56

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): source compile from `branch release-v1.56`
- Kubernetes version (use `kubectl version`): v1.25.2
- DV specification: 
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rbd-img-q9i6mvylu0fc
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 100Gi
    storageClassName: ecs-rbd-sc
    volumeMode: Block
  source:
    pvc:
      name: rbd-7tsdhrswuug6
      namespace: default
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: `storageClassName: ecs-rbd-sc` is based on ceph rbd csi plugin. which support snapshot feature.
