### ISSUE TITLE
Latest Version (v1.56.1) does not import images with k3d 

### ISSUE THREAD

**Issue by Vithor112** [kubevirt/containerized-data-importer#2830]
**What happened**:
After creating a cluster with k3d, and installing kubevirt version `v1.0.0` and CDI v1.56.1, I created a PVC with a CDI image associated with it, but it does not create the importer to download it, then if I try to create a VM bound to the PVC, the VM is initialized however it's unresponsive. 
If I change the pvc accessModes to ReadWriteMany the VM does not even initialize 
Using the cdi version `v1.54.3`  fix the problem
Steps followed:
```
#!/bin/bash
# Create cluster
k3d cluster create --volume /var/run/kubevirt:/var/run/kubevirt:shared cluster1 --k3s-arg "--flannel-backend=host-gw@server:0";

# Setting up KubeVirt
export VERSION=v1.0.0;
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml;
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml;

# Setting up CDI 
export VERSION=v1.56.1
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml;
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml;
```
pvc_centos.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "example-centos7"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
#  storageClassName: hostpath
```

vm.yaml
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: centos
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        resources:
          requests:
            memory: 10240M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: example-centos7
      - cloudInitNoCloud:
          userData: |
            #cloud-config 
            user: centos 
            password: test
            hostname: centos
            ssh_pwauth: True 
            disable_root: false
        name: cloudinitdisk
``` 

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):  `v1.56.1`
- Kubernetes version (use `kubectl version`): 
```
 Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.4+k3s1
```

- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```

- Kernel (e.g. `uname -a`):  `Linux 5.15.0-78-generic #85~20.04.1-Ubuntu`

**Comment by alromeros** [comment]
Hey @Vithor112, thanks for opening this issue. 

Currently, PVCs are not meant to be used directly with import annotations. CDI generally uses DataVolumes (https://github.com/kubevirt/containerized-data-importer/blob/main/doc/datavolumes.md) as abstractions of these PVCs, and creates them with all the required annotations for import/upload/clone to happen.

That said, I recommend creating a DV with the proper import source instead, like:

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "example-centos7"
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: hostpath
  source:
    http:
      url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
```

After creating the DV, CDI will handle the creation of a PVC and all the import-related steps. If the PVC is stuck again, the `k3d describe pvc`or `k3d describe dv` dumps would help for debugging purposes.

Hope this helps!
