### ISSUE TITLE
Pod Uploading local image get stuck 

### ISSUE THREAD

**Issue by Vithor112** [kubevirt/containerized-data-importer#2848]
**What happened**:
After creating a volume with a centos local image and creating a vm that uses that dataVolume, the pod that upload the image get stuck, running indefinitely and the vm keep waiting in the provisioning state 

**What you expected to happen**:
That the vm would be provisioned and created normally.

**How to reproduce it (as minimally and precisely as possible)**:
Download the image from [imageCentos]( https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2)
Then execute 
`kubectl virt image-upload dv centos --access-mode ReadWriteOnce --size=30Gi --image-path=CentOS-7-x86_64-GenericCloud.qcow2`
And create a vm with the following manifest
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: centos
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - name: cloudinitdisk
            disk:
              bus: virtio
        resources:
          requests:
            memory: 25Gi
      volumes:
      - dataVolume:
          name: centos
        name: datavolumedisk1
      - cloudInitNoCloud:
          secretRef: 
            name: mysecret
        name: cloudinitdisk
```

**Additional context**:
I successfully created a VM using a dataVolume that imported from the url used to download the image.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):  `v1.56.1`
- Kubernetes version (use `kubectl version`): 
```
 Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.4+k3s1
```

- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```

- Kernel (e.g. `uname -a`):  `Linux 5.15.0-78-generic #85~20.04.1-Ubuntu`

**Comment by awels** [comment]
Can you specify your storage type? Is it local storage?

**Comment by Vithor112** [comment]
Hi @awels , I don't know If I really understand what you meant. It's all in my machine and the image is on my disk.

**Comment by Vithor112** [comment]
It's
`local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  15d`

**Comment by awels** [comment]
Okay so it is waiting for the first consumer, since I am assuming your cluster only has a single node, we can force bind it by adding `--force-bind` to the image-upload command, this should bind the PVC and allow the upload to complete.

**Comment by Vithor112** [comment]
Hi @awels . 
So I tried to execute with the flag as you said but the behavior is the same:
```
ls -l | grep "Cent"
-rw-rw-r--  1 vpileco vpileco 902889472 ago 15 11:56 CentOS-7-x86_64-GenericCloud.qcow2
kubectl virt image-upload --force-bind dv centos --access-mode ReadWriteOnce --size=30Gi --image-path=./CentOS-7-x86_64-GenericCloud.qcow2
PVC default/centos not found 
DataVolume default/centos created
Waiting for PVC centos upload pod to be ready...
Pod now ready
uploadproxy URL not found
kubectl create -f tesVm.yaml 
virtualmachine.kubevirt.io/centos created
kubectl get all
Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
NAME                    READY   STATUS    RESTARTS   AGE
pod/cdi-upload-centos   1/1     Running   0          10m36s

NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/kubernetes          ClusterIP   10.43.0.1       <none>        443/TCP   16d
service/cdi-upload-centos   ClusterIP   10.43.110.124   <none>        443/TCP   10m36s

NAME                                AGE     STATUS         READY
virtualmachine.kubevirt.io/centos   5m56s   Provisioning   False

NAME                                        AGE     PHASE     IP    NODENAME   READY
virtualmachineinstance.kubevirt.io/centos   5m56s   Pending                    False

NAME                                PHASE         PROGRESS   RESTARTS   AGE
datavolume.cdi.kubevirt.io/centos   UploadReady   N/A                   10m37s
 kubectl logs cdi-upload-centos
I0816 19:00:53.873743       1 uploadserver.go:74] Running server on 0.0.0.0:8443

```

**Comment by awels** [comment]
It is actually different now the problem is now `uploadproxy URL not found`. Since you are probably running something like minikube you don't have a proper ingress that can be used by the upload, so you have to configure a [port-forward](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/upload.md#port-forwarding-via-the-api-server) and then pass the `--uploadproxy-url` that points to `localhost:<port>` where the port matches the port-forward

**Comment by awels** [comment]
Btw you can directly import from the centos source you don't have to download it first, you can do something like this:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: centos
spec:
  source:
    http:
      url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```
And it will directly import into your cluster.
