### ISSUE TITLE
The  pod importer-xxx does not start properly

### ISSUE THREAD

**Issue by yanruogu** [kubevirt/containerized-data-importer#2854]
**What happened**:

I create a vm1.yaml like this: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: mysql02
  namespace: vms
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mysql02
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.231.0.12\"]"
    spec:
      networks:
      - name: default
        pod: {}
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
          - name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 8192M
      volumes:
      - dataVolume:
          name: mysql02-dv
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: mysql02-dv
    spec:
      pvc:
        volumeMode: Block
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 200Gi
        storageClassName: ceph-rbd-kubevirt
      source:
        http:
          url: http://rgw.wanjiedata.cn/devops/images/ubuntu-22.04-cloud-agent.qcow2
```

then I create it:
```
kubectl create -f vm1.yaml
```
the mysql02 vmi will be create in vms namespace, but I execute follow command: 
```
root@yichang-10-200-0-215:~/kubevirt/vms# kubectl get pods -n vms
NAME                              READY   STATUS             RESTARTS         AGE
importer-mysql02-dv               0/1     CrashLoopBackOff   1 (2s ago)       9s
```
I check the log of  importer-mysql02-dv:
```
root@yichang-10-200-0-215:~/kubevirt/vms# kubectl logs -n vms importer-mysql02-dv
I0819 20:10:46.161854       1 importer.go:103] Starting importer
E0819 20:10:46.163447       1 importer.go:133] exit status 1, blockdev: cannot open /dev/cdi-block-volume: Permission denied

kubevirt.io/containerized-data-importer/pkg/util.GetAvailableSpaceBlock
        pkg/util/util.go:136
kubevirt.io/containerized-data-importer/pkg/util.GetAvailableSpaceByVolumeMode
        pkg/util/util.go:106
main.main
        cmd/cdi-importer/importer.go:131
runtime.main
        GOROOT/src/runtime/proc.go:250
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1594
```

and I don't know how to fix it.

PVC: 

```
root@yichang-10-200-0-215:~/kubevirt/vms# kubectl get pvc  -n vms
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
mysql02-dv               Bound    pvc-a130a0f3-8719-4842-ba17-fcd958c9677d   200Gi      RWX            ceph-rbd-kubevirt   7m54s

```

storageClass: 
```
root@yichang-10-200-0-215:~/kubevirt/vms# kubectl get sc
NAME                PROVISIONER        RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ceph-rbd-kubevirt   rbd.csi.ceph.com   Delete          Immediate           true                   36h

```
kubevirt: 
```
root@yichang-10-200-0-215:~/kubevirt/vms# kubectl get pods -n kubevirt
NAME                               READY   STATUS    RESTARTS       AGE
virt-api-56759cc7c4-hfssp          1/1     Running   1 (9h ago)     9h
virt-api-56759cc7c4-xp9qv          1/1     Running   0              9h
virt-controller-758f4bc8b5-gspcp   1/1     Running   5 (115m ago)   9h
virt-controller-758f4bc8b5-ntqbd   1/1     Running   0              9h
virt-handler-22ft5                 1/1     Running   0              9h
virt-handler-g8bmt                 1/1     Running   1 (9h ago)     9h
virt-handler-hkw97                 1/1     Running   0              9h
virt-handler-m67zj                 1/1     Running   0              9h
virt-handler-mvnnf                 1/1     Running   0              9h
virt-operator-78d75979-cmnhs       1/1     Running   0              2d6h
virt-operator-78d75979-cnvwk       1/1     Running   6 (117m ago)   40h

```

cdi: 
```
root@yichang-10-200-0-215:~/kubevirt/vms# kubectl get pods -n cdi
NAME                               READY   STATUS    RESTARTS       AGE
cdi-apiserver-77ddc6bb7d-qqpjf     1/1     Running   0              12h
cdi-deployment-5f77c76bfb-w6djs    1/1     Running   6 (118m ago)   9h
cdi-operator-6bff55bfcd-kmbzl      1/1     Running   6 (119m ago)   9h
cdi-uploadproxy-6b5b55d5cb-4xpn7   1/1     Running   0              9h

```

and the ceph keyring is client.admin

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.57.0
- Kubernetes version (use `kubectl version`): v1.28.0
- DV specification: N/A
- Cloud provider or hardware configuration:  N/A
- OS (e.g. from /etc/os-release): ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15
- Install tools: N/A
- Others: N/A
