### ISSUE TITLE
Blank disk with block volume mode stuck in ImportScheduled for WFFC storage class

### ISSUE THREAD

**Issue by lzang** [kubevirt/containerized-data-importer#2915]
**What happened**:
Created a blank DV with block volume mode for WFFC storage class, and found that it is stuck in ImportScheduled phase

**What you expected to happen**:
Expect the disk to be in Succeeded phase.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1. Have a storage class that supports block mode and WFFC
2. Create a blank DV as below:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: empty-disk
spec:
  source:
    blank: {}
  storage:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: block-sc
    volumeMode: Block
```
3. Observe that the dv is stuck in ImportScheduled phase.

**Additional context**:

Adding the annotation `cdi.kubevirt.io/storage.usePopulator: "false"`  to the dv allows the import to fall back to the old way and bypass the issue. 
    
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.57.0

**Comment by alromeros** [comment]
Hey @lzang, thanks for the issue! This might be a bug in our populators flow, I'll take a look and let you know when I find something.

**Comment by akalenyu** [comment]
I have opened a PR to hopefully address this; though I had no luck reproducing this without
the `bind.immediate` annotation

Would appreciate if you could confirm the logs in the PR description match the ones in your cdi-deployment pod

**Comment by awels** [comment]
The standard cdi should look something like this
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    featureGates:
    - HonorWaitForFirstConsumer
  imagePullPolicy: IfNotPresent
  infra:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  workload:
    nodeSelector:
      kubernetes.io/os: linux
```
