### ISSUE TITLE
Bug: Getting x509: certificate signed by unknown authority during image upload.

### ISSUE THREAD

**Issue by ajaydevtron** [kubevirt/containerized-data-importer#2926]
**What happened**:
I have installed the CDI using this user guide https://kubevirt.io/user-guide/operations/containerized_data_importer/#containerized-data-importer , but when we gonna create VMS with **DataVolumeTemplate** getting **certificate signed by unknown authority** in cdi-deployment logs and TLS handshake error in cdi-apiserver.

**cdi-apiserver log**

TLS handshake error from 10.244.1.6:35798: remote error: tls: bad certificate
 cdi-apiserver-5777ff7d9f-g6ls8: 2023/10/12 03:41:42 http: TLS handshake error from 10.244.1.5:46670: EOF
[Oct 12 2023 09:11:42 GMT+0530] cdi-apiserver-5777ff7d9f-g6ls8: 2023/10/12 03:41:42 http: TLS handshake error from 10.244.1.6:35812: EOF
[Oct 12 2023 09:11:42 GMT+0530] cdi-apiserver-5777ff7d9f-g6ls8: 2023/10/12 03:41:42 http: TLS handshake error from 10.244.1.6:35818: remote error: tls: bad certificate

**cdi-deployment log** 

{"level":"error","ts":"2023-10-12T03:42:05Z","msg":"Reconciler error","controller":"datavolume-import-controller","object":{"name":"fcos-os-disk-volume","namespace":"default"},"namespace":"default","name":"fcos-os-disk-volume","reconcileID":"d06564a2-be5c-4c04-a566-054b2a56e795","error":"Internal error occurred: failed calling webhook \"datavolume-mutate.cdi.kubevirt.io\": failed to call webhook: Post \"https://cdi-api.cdi.svc:443/datavolume-mutate?timeout=30s\": x509: certificate signed by unknown authority","stacktrace":"kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235"}

**What you expected to happen**:
It should able to upload image into PVC.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install kubevirt https://github.com/kubevirt/kubevirt/releases/tag/v1.0.0 using its CR and operator file into AKS(1.26 version) cluster.
2. Install CDI component from here https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.57.0 .
3. Try to create VMs with below configuration.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: my-fcos
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: fcos-os-disk-volume
    spec:
      source:
        registry:
          url:
            tedezed/ubuntu-container-disk:20.0
      storage:
        volumeMode: Block
        resources:
          requests:
            storage: 10Gi
        accessModes:
          - ReadWriteOnce
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - od
      tolerations:
      - effect: NoSchedule
        key: microservice
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      domain:
        devices:
          disks:
          - name: fcos-os-disk
            disk:
              bus: virtio
          - name: cloudinitvolume
            disk:
              bus: virtio
          rng: {}
        resources:
          requests:
            memory: 2048M
      volumes:
      - name: fcos-os-disk
        dataVolume:
          name: fcos-os-disk-volume
      - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False

```
4. Check the logs of cdi-apiserver , cdi-deployment , although i followed the this doc https://kubevirt.io/user-guide/operations/containerized_data_importer/#certificate-signed-by-unknown-authority  for same to upload image into PVC using virtctl cli but getting same .

**Additional context**:
Here my applied  CDI object .

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  finalizers:
    - operator.cdi.kubevirt.io
  generation: 2
  name: cdi
  resourceVersion: "440317893"
  uid: 2804eb00-0c0b-4729-95da-08885dfd05ef
spec:
  config:
    featureGates:
      - HonorWaitForFirstConsumer
  imagePullPolicy: IfNotPresent
  infra:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
  workload:
    nodeSelector:
      kubernetes.io/os: linux
status:
  conditions:
    - lastHeartbeatTime: 2023-10-11T11:04:51Z
      lastTransitionTime: 2023-10-11T11:04:51Z
      status: "False"
      type: Available
    - lastHeartbeatTime: 2023-10-11T11:04:51Z
      lastTransitionTime: 2023-10-11T11:04:51Z
      message: Started Deployment
      reason: DeployStarted
      status: "True"
      type: Progressing
    - lastHeartbeatTime: 2023-10-11T11:04:51Z
      lastTransitionTime: 2023-10-11T11:04:51Z
      status: "False"
      type: Degraded
  operatorVersion: v1.57.0
  phase: Deploying
  targetVersion: v1.57.0

```
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.57.0
- Kubernetes version (use `kubectl version`): 1.26
- DV specification: N/A
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): NA
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by ajaydevtron** [comment]
@awels Could you please help me out , I am block since 3 days.

**Comment by mhenriks** [comment]
Hi @ajaydevtron looks like cdi-apiserver is rejecting connections from kube-apiserver.  When `cdi-apiserver` receives a request from kube-apiserver, it will do the following:

1.  Validate the client cert against the certs stored in the ConfigMap `kube-system/extension-apiserver-authentication` in keys `client-ca-file` and `requestheader-client-ca-file`.  If the cert is not signed by one of those CAs or is expired, the request will be rejected.  You can check `kube-apiserver` `--proxy-client-cert-file` arg to validate the cert yourself.

2.  `cdi-apiserver` will also check that the CN (common name) in the client cert is listed in the `requestheader-allowed-names` key of `kube-system/extension-apiserver-authentication`.  You can check `kube-apiserver` `--requestheader-allowed-names` arg to validate against the values in the configmap.  Also make sure that this name matches the CN is step 1.

**Comment by ajaydevtron** [comment]
Hello @mhenriks 

As we are using Azure managed K8s (AKS) , and all the control plane components , eg **api-server** are abstracted , It can be challenging to pass the --proxy-client-cert-file args in api-server deployment in AKS. Also we can pass the **cdi-api** CN name into **--requestheader-allowed-names** of kube-system/extension-apiserver-authentication configmap but how we can rotate the API server pods.

Currently , After 24h cdi-deployment pod giving below error .

 {"level":"error","ts":"2023-10-14T04:21:43Z","logger":"controller.datavolume-import-controller","msg":"Unable to sync update dv meta","name":"fcos-os-disk-volume","error":"Internal error occurred: failed calling webhook \"datavolume-mutate.cdi.kubevirt.io\": failed to call webhook: Post \"https://cdi-api.cdi.svc:443/datavolume-mutate?timeout=30s\": x509: certificate has expired or is not yet valid: current time 2023-10-14T04:21:43Z is after 2023-10-12T11:05:26Z","stacktrace":"kubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*ReconcilerBase).syncUpdate\n\tpkg/controller/datavolume/controller-base.go:496\nkubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*ReconcilerBase).syncCommon\n\tpkg/controller/datavolume/controller-base.go:415\nkubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*ImportReconciler).syncImport\n\tpkg/controller/datavolume/import-controller.go:200\nkubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*ImportReconciler).sync\n\tpkg/controller/datavolume/import-controller.go:192\nkubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*ReconcilerBase).reconcile\n\tpkg/controller/datavolume/controller-base.go:399\nkubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*ImportReconciler).Reconcile\n\tpkg/controller/datavolume/import-controller.go:188\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235"}
 
 
 For this I had gone through this https://github.com/kubevirt/containerized-data-importer/issues/2695
 and tried to put below configuration in CDI object , but NO Luck 
 
```
 certConfig:
    ca:
      duration: 100000h
      renewBefore: 10000h
    server:
      duration: 80000h
      renewBefore: 10000h
```

Could you please help me here ?
