### ISSUE TITLE
Custom lifecycle hooks configured via CDIConfig

### ISSUE THREAD

**Issue by bc185174** [kubevirt/containerized-data-importer#3012]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

In https://github.com/kubevirt/containerized-data-importer/issues/2948 we found that the CDIs transient pods (k8s jobs) were not terminated when meshed with linkerd. The current workaround is to disable injection on these pods by propagating the annotation `linkerd.io/inject: disabled` from the `DataVolume` to the importer pods. Ultimatly, we would like linkerd to implement sidecars through native k8s functionality; however, this is only available in `v1.28.x` and users will be unlikely to take alpha version of security mesh provider.

**Describe the solution you'd like**:

Ability to add custom lifecycle hooks to the importer pods via `CDIConfig`.

```
lifecycle:
  preStop:
    exec:
       command:
       - /bin/bash
       - -c
       - curl -X POST http://localhost:4191/shutdown
```

**Describe alternatives you've considered**:

N/A

**Additional context**:
