### ISSUE TITLE
The image file's Virtual image size change when upload to dv with different size

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/containerized-data-importer#3095]
**What happened**:
A clear and concise description of what the bug **is**
In advance: the img file is a .mp4 file before ,I change the suffix to qcow2.
![image](https://github.com/kubevirt/containerized-data-importer/assets/49519342/590bda83-0882-4b06-9c85-03de31df2a99)

When I update it to a 1G dv with https://XXX/v1alpha1/upload-async it return Virtual image size is 1G+

![image](https://github.com/kubevirt/containerized-data-importer/assets/49519342/8229b4b4-4593-4874-b3ef-77621a0666da)

While I update it to a 2G dv, it also return Virtual image size is 2G+
![image](https://github.com/kubevirt/containerized-data-importer/assets/49519342/f4d4d1f8-25b6-429a-8c5a-7591d6a74075)

**What you expected to happen**:

I am puzzled why Virtual image size can change.IMO, It is get by qemu-img info.

By the way, this file just has suffix  .qcow2. I think we should return fmt error or something like it.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Maybe you can reproduce it by change a mp4 file suffix  to .qcow2, and upload it with v1alpha1/upload-async.
1) find a .mp4 file ,change it suffix to .qcow2
2) create dv and token
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: zal-test-5
  namespace: zal
spec:
  source:
    upload: {}
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10G
    storageClassName: rbd-ssd
    volumeMode: Block
```
3) uplod file with 
```
curl -v --insecure -H "Authorization: Bearer token" --data-binary @xxx/nlw-ssh.qcow2 https://ip/v1alpha1/upload-async -g
```

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.53
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
