### ISSUE TITLE
The CDI-deployment which is manager by cdi-operator misses one label's value

### ISSUE THREAD

**Issue by matthewei** [kubevirt/containerized-data-importer#3125]
**What happened**:
I found the "cdi-deployment-*****" pod's label `cdi.kubevirt.io` missing value when i check the pod of `cdi-deployment-5c4d497d8-ljbxg`. As is known to all, the "cdi-deployment-*****" pod is managed by `cdi-operator` and the `cdi-apiserver`'s label is normal.

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-05T01:59:05Z"
  generateName: cdi-deployment-5c4d497d8-
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-operator
    cdi.kubevirt.io: ""
    operator.cdi.kubevirt.io/createVersion: v1.53.0
    pod-template-hash: 5c4d497d8
    prometheus.cdi.kubevirt.io: "true"
  name: cdi-deployment-5c4d497d8-ljbxg
  namespace: cdi
```

![image](https://github.com/kubevirt/containerized-data-importer/assets/86186853/60d292ac-9435-4b3e-bed6-7e8f9d69b2cc)

**What you expected to happen**:

```yaml
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-operator
    cdi.kubevirt.io: "cdi-deployment"
    operator.cdi.kubevirt.io/createVersion: v1.53.0
    pod-template-hash: 5c4d497d8
    prometheus.cdi.kubevirt.io: "true"
```

![image](https://github.com/kubevirt/containerized-data-importer/assets/86186853/643a40e3-da05-4820-811c-b73f08855fe3)

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
