### ISSUE TITLE
After configuring the annotation  annotations cdi.kubevirt.io/storage.pod.retainAfterCompletion: "true", the intended behavior or result was not observed as expected.

### ISSUE THREAD

**Issue by tghfly** [kubevirt/containerized-data-importer#3130]
**What happened**:
Annotation: cdi.kubevirt.io/storage.pod.retainAfterCompletion set to true specifies that the CDI data transfer pod should remain intact following successful completion of the operation, but this behavior applies exclusively when the data source is an HTTP source. When the source is a PVC, even if this annotation is present, pods with names starting with 'prep-' will be automatically deleted upon successful completion, not retained.

**What you expected to happen**:
When the source is a PVC, the pods starting with 'prep-' should be retained after completion.

**How to reproduce it (as minimally and precisely as possible)**:
The following YAML, upon execution，the pods starting with 'prep-' should be retained after completion.
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cloned-dv2
  namespace: test
  annotations:
    cdi.kubevirt.io/storage.pod.retainAfterCompletion: "true"
spec:
  source:
    pvc:
      namespace: default
      name: img-cirros-0.5.1
  storage:
    volumeMode: "Block"
    storageClassName: "ceph-hdd-block"
    accessModes:
      - ReadWriteMany
```
The following YAML, upon execution, results in the Pod being retained after its completion.
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-pod-retain
  annotations:
    cdi.kubevirt.io/storage.pod.retainAfterCompletion: "true"
spec:
  source:
    http:
      url: "http://dl.demo.com/images/cirros-0.5.1-x86_64-disk.img"
  pvc:
    storageClassName: "ceph-hdd-block"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
```

**Additional context**:

**Environment**: 
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.58.1
- Kubernetes version (use `kubectl version`): 1.27.6
- DV specification: spec.source.pvc
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 5.10.0-136
- Install tools: N/A
- Others: N/A
