### ISSUE TITLE
CDI cannot import datavolumes

### ISSUE THREAD

**Issue by keepthemomentum** [kubevirt/containerized-data-importer#3160]
I'm running kubevirt VM's for some time, using CDI for importing dynamic provisioning of datavolumes. I having issues creating new VM's when importing datavolumes. 
First it creates a PV and PVC, both are bound. But then, it attempts to create a scratch PVC which is in pending state leaves the VM in 'provisioning' state. 

```
NAME                                  STATUS    VOLUME                       CAPACITY   ACCESS MODES   STORAGECLASS                  VOLUMEATTRIBUTESCLASS   AGE
data-volume-enc01           Bound     enc01-datavolume   10Gi       RWO            local-storage                 <unset>                 28m
data-volume-christian-enc01-scratch   Pending                                                          local-storage                 <unset>                 28m

Describing the datavolume gives 'scratch space required and none found'
    Message:               scratch space required and none found
    Reason:                Scratch space required
```

This is the template which worked fine, now it's not.

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage 
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: enc01-datavolume
  labels:
    type: local
spec:
  storageClassName: local-storage 
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/volume/enc01"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - app-dev-dc
---            
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-enc01 
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-enc01 
    spec:
      nodeSelector:
        kubernetes.io/hostname: app-dev-dc
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: datavolume
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: kubevirt-bridge
            bridge: {}  
          - name: default
            bridge: {}     
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: kubevirt-bridge
        multus:
          networkName: ovs-kubevirt-bridge-static-enc01 
      - name: default
        pod: {}      
      volumes:
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: vm-cloud-config
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true                    
        - name: datavolume
          dataVolume:
            name: data-volume-enc01
  
  dataVolumeTemplates:
  - metadata:
      name: data-volume-enc01
    spec:
      pvc:
        storageClassName: local-storage
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      source:
        http:
          url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
```

**Comment by awels** [comment]
Can you describe the scratch pvc, and see why it is not getting bound? Maybe ran out of space?

**Comment by keepthemomentum** [comment]
> Can you describe the scratch pvc, and see why it is not getting bound? Maybe ran out of space?

This is how it looks.

Name:          data-volume-enc01-scratch
Namespace:     default
StorageClass:  local-storage
Status:        Pending
Volume:        
Labels:        app=containerized-data-importer
               app.kubernetes.io/component=storage
               app.kubernetes.io/managed-by=cdi-controller
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       importer-data-volume-enc01
Events:
  Type    Reason               Age                  From                         Message
  ----    ------               ----                 ----                         -------
  Normal  WaitForPodScheduled  87s (x162 over 41m)  persistentvolume-controller  waiting for pod importer-data-volume-enc01 to be scheduled

**Comment by awels** [comment]
Okay so based on that I am assuming that the `local-storage` storage class is WaitForFirstConsumer volume mode. The message indicates that the pod is not being scheduled. Is the pod created just in scheduling, or does the pod not exist at all? If it doesn't exist, can you check the cdi `cdi-deployment-xxxx-yyy` logs in the cdi namespace to see why the pod is not being created.

**Comment by keepthemomentum** [comment]
> Okay so based on that I am assuming that the `local-storage` storage class is WaitForFirstConsumer volume mode. The message indicates that the pod is not being scheduled. Is the pod created just in scheduling, or does the pod not exist at all? If it doesn't exist, can you check the cdi `cdi-deployment-xxxx-yyy` logs in the cdi namespace to see why the pod is not being created.

Yes, it’s local-storage with waitforfirstconsumer. The importer pod is in ‘scheduling’ but no virt-launcher pod for the virtual machine. I will post the cdi-deployment logs now.

**Comment by awels** [comment]
Can you describe the importer pod, if it is in scheduling then it should tell you why. The reason the PVC is not getting bound is because there is no pod using it (its the importer that would use it). So what is the reason the importer pod is not scheduling?

**Comment by keepthemomentum** [comment]
> Can you describe the importer pod, if it is in scheduling then it should tell you why. The reason the PVC is not getting bound is because there is no pod using it (its the importer that would use it). So what is the reason the importer pod is not scheduling?


The importer pod is in  'pending' state

```
NAME                                   READY   STATUS    RESTARTS   AGE
importer-data-volume-enc01   0/1     Pending   0          86m
```


```
Name:             importer-data-volume-enc01
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=containerized-data-importer
                  app.kubernetes.io/component=storage
                  app.kubernetes.io/managed-by=cdi-controller
                  cdi.kubevirt.io=importer
                  prometheus.cdi.kubevirt.io=true
Annotations:      cdi.kubevirt.io/storage.createdByController: yes
                  linkerd.io/inject: disabled
                  sidecar.istio.io/inject: false
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    PersistentVolumeClaim/data-volume-enc01
Containers:
  importer:
    Image:           quay.io/kubevirt/cdi-importer:v1.59.0
    Port:            8443/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      -v=1
    Limits:
      cpu:     750m
      memory:  600M
    Requests:
      cpu:     100m
      memory:  60M
    Environment:
      IMPORTER_SOURCE:               http
      IMPORTER_ENDPOINT:             https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
      IMPORTER_CONTENTTYPE:          kubevirt
      IMPORTER_IMAGE_SIZE:           10Gi
      OWNER_UID:                     4d68a46f-c69a-496b-b19d-de3918e85b0a
      FILESYSTEM_OVERHEAD:           0.055
      INSECURE_TLS:                  false
      IMPORTER_DISK_ID:              
      IMPORTER_UUID:                 
      IMPORTER_PULL_METHOD:          
      IMPORTER_READY_FILE:           
      IMPORTER_DONE_FILE:            
      IMPORTER_BACKING_FILE:         
      IMPORTER_THUMBPRINT:           
      http_proxy:                    
      https_proxy:                   
      no_proxy:                      
      IMPORTER_CURRENT_CHECKPOINT:   
      IMPORTER_PREVIOUS_CHECKPOINT:  
      IMPORTER_FINAL_CHECKPOINT:     
      PREALLOCATION:                 false
    Mounts:
      /data from cdi-data-vol (rw)
      /scratch from cdi-scratch-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9ztl6 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  cdi-data-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-volume-enc01
    ReadOnly:   false
  cdi-scratch-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-volume-enc01-scratch
    ReadOnly:   false
  kube-api-access-9ztl6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  7m33s (x19 over 83m)  default-scheduler  0/5 nodes are available: 1 node(s) didn't find available persistent volumes to bind. preemption: 0/5 nodes are available: 1 Preemption is not helpful for scheduling, 4 No preemption victims found for incoming pod.
```

**Comment by awels** [comment]
Great, so the pod is pending because it can't find a persistent volume to bind and the persistent volume claim is pending because no pod is using it. So that suggests the problem can be found in the provisioner (it should provision the volume, but it is not) Can you check the provisioner logs to see why it can't create the volume?

**Comment by awels** [comment]
No it is in the logs of the `local-storage` provisioner. I am assuming it is installed in its own namespace somewhere.

**Comment by keepthemomentum** [comment]
> No it is in the logs of the `local-storage` provisioner. I am assuming it is installed in its own namespace somewhere.

Its coming from the storage class, i couldn't check the logs for the storage class. 

```
Name:            local-storage-enc01
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-storage-christian-enc01"},"provisioner":"kubernetes.io/no-provisioner","reclaimPolicy":"Retain","volumeBindingMode":"WaitForFirstConsumer"}

Provisioner:           kubernetes.io/no-provisioner
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```

**Comment by keepthemomentum** [comment]
I also see this error in the cdi-deployment pod.

```
{"level":"info","ts":"2024-04-02T14:41:01Z","msg":"Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler","controller":"datavolume-import-controller","object":{"name":"data-volume-enc01","namespace":"default"},"namespace":"default","name":"data-volume-enc01","reconcileID":"03f58317-5671-4927-9e1d-90c744de4d0f"}

{"level":"error","ts":"2024-04-02T14:41:01Z","msg":"Reconciler error","controller":"datavolume-import-controller","object":{"name":"data-volume-enc01","namespace":"default"},"namespace":"default","name":"data-volume-enc01","reconcileID":"03f58317-5671-4927-9e1d-90c744de4d0f","error":"Operation cannot be fulfilled on datavolumes.cdi.kubevirt.io \"data-volume-enc01\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
```

**Comment by akalenyu** [comment]
Are you doing static provisioning? I noticed `kubernetes.io/no-provisioner` on the storage class.
Is there an extra PersistentVolume available to be used for scratch space?

**Comment by keepthemomentum** [comment]
> Are you doing static provisioning? I noticed `kubernetes.io/no-provisioner` on the storage class. Is there an extra PersistentVolume available to be used for scratch space?

Yes, i do.
1. I create a storage class with 'no-provisioner' for creating local/host-path persistent volumes. I use 'WaitForFirstConsumer' as the volumebindingmode in storageclass to delay volumebinding.
2. A persistent volume local/host-path (this will be a directory with appropriate permission and ownership) on the server
3. Then, use datavolume tempates (pvc) to import the OS image. 

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: virtualmachine-pv
  labels:
    type: local
spec:
  storageClassName: local-storage 
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/datavolume/server"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - app-dev-dc
```
