### ISSUE TITLE
Longhorn and contentType 'archive' don't work together

### ISSUE THREAD

**Issue by ianb-mp** [kubevirt/containerized-data-importer#3168]
**What happened**:

When I use `contentType: archive` together with Longhorn storage class for the PVC, my VM consistently fails to launch with error:
```
Warning  SyncFailed        115s (x16 over 4m39s)  virt-handler               preparing host-disks failed: unable to create /var/run/kubevirt-private/vmi-disks/datavolumedisk1-xxxx/disk.img, not enough space, │
│  demanded size 67108864 B is bigger than available space 57167872 B, also after taking 10 % toleration into account     
```

**What you expected to happen**:

Using archive type and Longhorn together should be possible.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

- It doesn't matter what size I set the PVC to, I get the same error with the available space just a bit lower than what I requested.
- `archive` works fine if I use a storage class other than longhorn e.g. local-path
- Longhorn storage works fine for any data source other than archive: e.g. I use another PVC as the source; or I use HTTP source but specify a `qcow2` image rather than tar file, comment `contentType: archive`, and adjust storage size etc.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.59.0
- Kubernetes version (use `kubectl version`): v1.27.10+rke2r1
- DV specification: 
```yaml
  dataVolumeTemplates:
  - metadata:
      name: vm-archive-test
    spec:
      source:
          http:
             url: "http://10.2.3.2/rocky/archive_test/archive2.tar"
      contentType: archive
      pvc:
        #storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi
```
(Longhorn is set as the default storage class)

- Cloud provider or hardware configuration: bare metal, x86_64
- OS (e.g. from /etc/os-release): Rocky Linux 9.3
- Kernel (e.g. `uname -a`): 5.14.0-362.18.1.el9_3.x86_64
- Install tools: N/A
- Others: N/A
