### ISSUE TITLE
CDI import from HTTP source gives certificate errors.

### ISSUE THREAD

**Issue by keepthemomentum** [kubevirt/containerized-data-importer#3443]
I'm trying to import ubuntu cloud image using CDI datavolumes. I get the following certificate error. 
It's been working fine, but not now. I have updated CDI operator and cdi-cr from v1.59.0 to v1.60.1 but no luck.

`Warning  Error             2m41s (x5 over 5m44s)  datavolume-import-controller  Unable to connect to http data source: HTTP request errored: Get "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img": tls: failed to verify certificate: x509:`

Below is my VM template, I'm using hostpath volumes. I have tried different URL's to pull the cloud image, but i get the same error message. 

+++++++++++++++++++++++++++++

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-stg-vm01
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stg-vm01-datavolume
  labels:
    type: local
spec:
  storageClassName: local-storage-stg-vm01
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/datavolume/stg-vm01"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vm01-stg-se-hq
```
---
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-stg-vm01
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-stg-vm01
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm01-stg-se-hq
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: datavolume
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: kubevirt-bridge
            bridge: {}
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: kubevirt-bridge
        multus:
          networkName: ovs-kubevirt-bridge-static-stg-vm01
      - name: default
        pod: {}
      volumes:
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: vm-cloud-config
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
        - name: datavolume
          dataVolume:
            name: data-volume-stg-vm01

  dataVolumeTemplates:
  - metadata:
      name: data-volume-stg-vm01
    spec:
      pvc:
        storageClassName: local-storage-stg-vm01
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
      source:
        http:
          url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
```
