### ISSUE TITLE
Automatically create NetworkPolicies if NetworkPolicy usage is detected

### ISSUE THREAD

**Issue by jrcichra** [kubevirt/containerized-data-importer#3497]
**Is your feature request related to a problem? Please describe**:
When specifying a URL to import either via `virtctl image-upload` or on a `dataVolumeTemplate` and the cluster makes use of NetworkPolicies, users are required to apply a NetworkPolicy in their namespace to make the import work.

For `dataVolumeTemplate` of an Ubuntu ISO:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ubuntu-iso-download
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
  podSelector:
    matchLabels:
      app: containerized-data-importer
  policyTypes:
    - Egress
```

For `virtctl image-upload`:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-image-upload
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cdi
    - ports:
        - port: 443
          protocol: TCP
  podSelector:
    matchLabels:
      app: containerized-data-importer
  policyTypes:
    - Ingress
```

**Describe the solution you'd like**:
An option for KubeVirt CDI to detect if NetworkPolicies are being used in a namespace. If they are, add one to allow containerized-data-importer to download the image. If not, don't apply a NetworkPolicy.

**Describe alternatives you've considered**:
For now users are able to specify the above NetworkPolicies to import their VM.

**Additional context**:
