### ISSUE TITLE
Setting a TLS secret for the cdi-uploadproxy ingress breaks Portworx for Kubevirt

### ISSUE THREAD

**Issue by kreeuwijk** [kubevirt/containerized-data-importer#3515]
**What happened**:
When deploying a new Kubevirt cluster with an ingress resource defined for the CDI upload-proxy, if this resource includes TLS configuration for HTTPS support, it will be impossible to successfully start Kubevirt VMs when using Portworx as the CSI.

**What you expected to happen**:
`virt-launcher` pod should not hang on a virsh domain creation issue, seemingly caused by some interplay between the datavolume resource, the cdi-uploadproxy and Portworx.

**How to reproduce it (as minimally and precisely as possible)**:

Take the following example ingress for the CDI upload-proxy:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cdi-uploadproxy
  namespace: cdi
spec:
  ingressClassName: nginx
  rules:
  - host: cdi-uploadproxy.company.domain
    http:
      paths:
      - backend:
          service:
            name: cdi-uploadproxy
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - virt-exportproxy.company.domain
    secretName: virt-exportproxy-tls
```

the certificate for the ingress is issued by cert-manager, using a self-signed issuer:
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cdi-selfsigned-issuer
  namespace: cdi
spec:
  selfSigned: {}
```

this causes the following errors to get logged in the `cdi-deployment` pod:
```
W1106 10:50:43.178639       1 reflector.go:547] pkg/cache/internal/informers.go:106: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:cdi:cdi-sa" cannot list resource "secrets" in API group "" at the cluster scope
E1106 10:50:43.178675       1 reflector.go:150] pkg/cache/internal/informers.go:106: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:cdi:cdi-sa" cannot list resource "secrets" in API group "" at the
 cluster scope
```

This seems to be caused by the `cdi` ClusterRole only having `create` permissions for secrets. I don't know if it is a contributing factor to the issue though.

Starting a Kubevirt VM that is using a DataVolume backed by a Portworx v4 Service volume then will not work. During early startup of the `virt-launcher` pod, the process hangs and eventually times out with a `panic: timed out waiting for domain to be defined` error (see screenshot).

![Screenshot 2024-11-02 at 16 35 56](https://github.com/user-attachments/assets/2126d7a9-0f3e-4a63-8d15-64d31d5c11d6)

If the TLS configuration is removed from the ingress resource and the CDI and Kubevirt pods are restarted, VMs start up normally. It also seems that once this works once, even adding the TLS config back in, still allows VMs to work.

**Additional context**:
Also reporting this issue to Portworx as they may need to change something on their side. When I used a different CSI (I tried Rook-Ceph and Azure Disk), the issue does not occur.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):1.60.2
- Kubernetes version (use `kubectl version`): 1.29.9
- DV specification:
```
    - metadata:
        creationTimestamp: null
        name: ubuntu-2204
      spec:
        source:
          registry:
            url: >-
              docker://gcr.io/spectro-images-public/release/vm-dashboard/os/ubuntu-container-disk:22.04
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 50Gi
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 22.04.5 LTS
- Kernel (e.g. `uname -a`): 6.5.0-26-generic
- Install tools: Spectro Cloud Palette
- Others:
  - Portworx Enterprise 3.1.5
  - Kubevirt 1.2.0 (also reproduced on 1.3.1)
  - Nginx 1.10.0
  - Cert-manager 1.11.0
