### ISSUE TITLE
Random Storage Class Selection During Host-Assisted Snapshot Restore

### ISSUE THREAD

**Issue by TheRealSibasishBehera** [kubevirt/containerized-data-importer#3530]
**What happened**:
During host-assisted snapshot restore operations, CDI creates intermediate PVCs with randomly selected storage class (matching only the CSI driver), ignoring both the DataVolume's specified storage class and the source PVC's storage class. This leads to restore failures when an incompatible storage class is selected.

Error seen:

in the host-assisted pvc 
```
ProvisioningFailed: failed to provision volume with StorageClass "ms-ext4-3-replicas-local": 
rpc error: code = InvalidArgument desc = error in response: status code '400 Bad Request', content: 'RestJsonError { details: "", message: "SvcError :: ClonedSnapshotVolumeThin: Cloned snapshot volumes must be thin provisioned", kind: InvalidArgument }'
```

**What you expected to happen**:

CDI should follow a predictable storage class selection priority during host-assisted snapshot restore:

- Use the storage class specified in the DataVolume
- Fall back to source PVC's storage class
- Use default storage class with matching driver
- Only as last resort, use any matching storage class

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

Create a snapshot from existing PVC:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: blank-datavolume-snapshot
spec:
  source:
    persistentVolumeClaimName: blank-datavolume
```

Create DataVolume to restore from snapshot:

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: new-datavolume-from-snapshot
spec:
  source:
    snapshot:
      name: blank-datavolume-snapshot
      namespace: default
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: ms-xfs-snapshot-restore
```

Observe intermediate PVC creation:

```
kubectl get pvc <uuid>-host-assisted-source-pvc -o yaml
```

Shows storage class ms-ext4-3-replicas-local instead of the specified ms-xfs-snapshot-restore

**Additional context**:

The current implementation in getStorageClassCorrespondingToSnapClass only matches on CSI driver and takes the first match:

```
func (r *SnapshotCloneReconciler) getStorageClassCorrespondingToSnapClass(driver string) (string, error) {
    matches := []storagev1.StorageClass{}
    // Lists all storage classes
    storageClasses := &storagev1.StorageClassList{}
    if err := r.client.List(context.TODO(), storageClasses); err != nil {
        return "", errors.New("unable to retrieve storage classes")
    }
    // Just matches on driver and takes first match
    for _, storageClass := range storageClasses.Items {
        if storageClass.Provisioner == driver {
            matches = append(matches, matches)
        }
    }
    if len(matches) > 1 {
        return matches[0].Name, nil
    }
    //...
}
```

Suggested Changes:

Prioritized Storage Class Selection:

1. First: Use DV's specified storage class (if matches driver)
2. Second: Try source PVC's storage class (from snapshot)
3. Third: Try default storage class (with matching driver)
4. Last Resort: Any matching storage class

or 

Have a way for the user to configure behaviour for intermediate pvc

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):v1.60.3
- Kubernetes version (use `kubectl version`): 
Server: v1.22.17
Client: v1.31.0
- DV specification: 
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: new-datavolume-from-snapshot
  namespace: default
spec:
  source:
    snapshot:
      name: blank-datavolume-snapshot
      namespace: default
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: ms-xfs-snapshot-restore
```
    
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: 
- Others: 
   Multiple storage classes using same CSI driver `io.openebs.csi-mayastor`:
  - ms-ext4-3-replicas-local
  - ms-xfs-snapshot-restore
  - VolumeSnapshot feature enabled and CRDs installed
