### ISSUE TITLE
PVC Image Upload Volume Node Affinity Conflict

### ISSUE THREAD

**Issue by CodeBeholderKASM** [kubevirt/containerized-data-importer#3631]
I have KubeVirt and CDI running on OKE, but when attempting to use virtctl to do an image-upload of a PVC the upload pod reports this:

```conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-02-10T18:49:37Z"
    message: '0/3 nodes are available: 3 node(s) had volume node affinity conflict.
      preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
```

I followed the advice of this ticket (https://github.com/kubevirt/containerized-data-importer/issues/3287) and changed my storageclass to be waitForFirstConsumer with the annotation mentioned in the comment, but my PV are still assigned to different nodes.

storageclass:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
  name: kasm-storage
provisioner: blockvolume.csi.oraclecloud.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

The PVs:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
csi-d0dbc61d-b8c5-48a4-9c6d-c74f072d9c0d   50Gi       RWO            Delete           Bound    cdi/kasm-ubuntu           kasm-storage   <unset>                          153m
csi-e7bf2880-5d50-4227-aca0-e91bfb22b42b   50Gi       RWO            Delete           Bound    cdi/kasm-ubuntu-scratch   kasm-storage   <unset>                          153m

```

Thanks for the help!

k8s version:
```
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1
```

CDI Version:
```
$ kubectl get deployments -n cdi -o jsonpath="{.items[0].metadata.labels.operator\.cdi\.kubevirt\.io/createVersion}"
v1.61.1
```

KubeVirt Version:
```
$ kubectl get deployments -n kubevirt -o jsonpath="{.items[0].metadata.labels.app\.kubernetes\.io/version}"
v1.4.0
```

VirtCTL Version:
```
$ virtctl version
Client Version: version.Info{GitVersion:"v1.4.0", GitCommit:"9b9b3d4e7b681af96ca1b6b6a5cea75e2f05ce5b", GitTreeState:"clean", BuildDate:"2024-11-13T08:23:36Z", GoVersion:"go1.22.8 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.4.0", GitCommit:"9b9b3d4e7b681af96ca1b6b6a5cea75e2f05ce5b", GitTreeState:"clean", BuildDate:"2024-11-13T09:51:17Z", GoVersion:"go1.22.8 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
```
