### ISSUE TITLE
/data/disk.img permission denied when importing a qcow2 image on a iSCSI PV

### ISSUE THREAD

**Issue by MichaelTrip** [kubevirt/containerized-data-importer#3632]
**What happened**:
Importing a qcow2 image with cdi on a iscsi PV gives a `emu-img: /data/disk.img: error while converting raw: Could not create '/data/disk.img': Permission denied`. This comes from the importer prime pod. 

**What you expected to happen**:
I expect the disk import to successfully import a qcow2 image. This works when using a NFS based PV/PVC. 

**How to reproduce it (as minimally and precisely as possible)**:

Using the following snippit in the `VirtualMachine`  manifest:

```yaml
  dataVolumeTemplates:
    - metadata:
        name: debian-vm-pvc
        creationTimestamp: null
      spec:
        storage:
          resources:
            requests:
              storage: 15Gi
          accessModes:
            - ReadWriteOnce
          storageClassName: synology-iscsi
        source:
          http:
            url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
```

**Additional context**:
The logs of the importer prime pod:
```
I0212 10:46:10.285255       1 prometheus.go:78] 82.89
I0212 10:46:11.285422       1 prometheus.go:78] 88.56
I0212 10:46:12.285454       1 prometheus.go:78] 94.25
I0212 10:46:13.285560       1 prometheus.go:78] 99.92
I0212 10:46:13.673703       1 data-processor.go:247] New phase: Convert
I0212 10:46:13.673721       1 data-processor.go:253] Validating image
E0212 10:46:13.680190       1 prlimit.go:156] failed to kill the process; os: process already finished
I0212 10:46:13.680299       1 qemu.go:115] Running qemu-img with args: [convert -t writeback -p -O raw /scratch/tmpimage /data/disk.img]
I0212 10:46:13.684857       1 qemu.go:273] 0.00
E0212 10:46:13.686150       1 prlimit.go:178] qemu-img failed output is:
E0212 10:46:13.686177       1 prlimit.go:179]     (0.00/100%)


E0212 10:46:13.686184       1 prlimit.go:180] qemu-img: /data/disk.img: error while converting raw: Could not create '/data/disk.img': Permission denied

E0212 10:46:13.686199       1 prlimit.go:156] failed to kill the process; os: process already finished
E0212 10:46:13.686240       1 data-processor.go:243] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
	pkg/system/prlimit.go:182
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:112
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:116
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:161
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:272
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
could not convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:124
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:161
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:272
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:274
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:207
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
E0212 10:46:13.686425       1 importer.go:183] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
	pkg/system/prlimit.go:182
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:112
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:116
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:161
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:272
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
could not convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:124
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:161
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:272
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:274
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:207
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:149
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.59.1 (upgrading to v1.60.x gives errors when using longhorn
- Kubernetes version (use `kubectl version`): v1.31.5
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Talos Linux v1.8.4
- Kernel: `6.6.64-talos #1 SMP Wed Dec 11 15:33:07 UTC 2024 x86_64 Linux`
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
Can a regular pod write to a PVC provisioned by `synology-iscsi`?
I suspect it can't, hence the permission issue. It's possible that fsGroup handling is not set up properly on the CSIDriver level.

BTW, could you attach the storageclass object? CDI uses the provisioner string to identify volume/access mode
but I don't think we ever added those for this particular provisioner.

**Comment by MichaelTrip** [comment]
@akalenyu i have created this deployment and pvc:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-sleep-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-sleep-pod
  template:
    metadata:
      labels:
        app: secure-sleep-pod
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: secure-sleep-container
        image: busybox
        command: ["sleep"]
        args: ["infinity"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: secure-sleep-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secure-sleep-pvc
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

I can write to `/data` :

```bash
$ k exec -it secure-sleep-deployment-b8fc8846b-wxjnn -- /bin/sh
~ $ cd /data
/data $ echo bla > testfile
/data $ cat testfile 
bla
/data $ 
```

This is the storageclass i use:

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: synology-iscsi
parameters:
  csi.storage.k8s.io/fstype: ext4
  dsm: 10.99.102.101
  location: /volume1
  protocol: iscsi
provisioner: csi.san.synology.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
````

If i can be of more assistance, please let me know!

**Comment by akalenyu** [comment]
Hmm maybe try without runAsGroup to make it more similar to the CDI importer pod?
Really interesting as this is unlikely to be the culprit

And maybe try to add in the seccomp profile as well
(really just trying to spin an equivalent pod since that should fail to write too)
```yaml
  spec:
    containers:
...
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 107
        seccompProfile:
          type: RuntimeDefault
...
    securityContext:
      fsGroup: 107
...
    volumes:
    - name: cdi-data-vol
      persistentVolumeClaim:
        claimName: prime-...
    - name: cdi-scratch-vol
      persistentVolumeClaim:
        claimName: prime-...-scratch
```

**Comment by akalenyu** [comment]
Super weird.. can you attach the CSIDriver object for the driver?

**Comment by MichaelTrip** [comment]
@akalenyu here you go:

```yaml
❯ oc get csidrivers.storage.k8s.io csi.san.synology.com -oyaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
  creationTimestamp: "2025-02-12T09:56:34Z"
  name: csi.san.synology.com
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
```

**Comment by akalenyu** [comment]
Right so `fsGroupPolicy: ReadWriteOnceWithFSType` means that in certain cases, kubelet will not perform chmod/chown
(no fsType on the storage class/RWX volumes)
So that is likely the issue. Not sure why it works under the busybox image/securityContext

**Comment by awels** [comment]
So his storage class has `csi.storage.k8s.io/fstype: ext4` which is the new version of `fsType: ext4` which should pass the fsType to the external provisioner sidecar, and the chmod should happen.

Can you grab the yaml of the importer pod that is failing, and replace the command with a sleep, start it and exec into that pod, and see if you can write to /data?

**Comment by akalenyu** [comment]
Yeah that would help. Also what is the `id` output from inside the busybox?

**Comment by MichaelTrip** [comment]
@akalenyu the id in the busybox pod:
```
❯ k exec -it secure-sleep-deployment-9c64b6595-jds8g -- /bin/sh
~ $ id
uid=107 gid=0(root) groups=0(root),107
```

@awels this is the pod i created:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdi-data-vol
  namespace: virtualmachines
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  annotations:
    cdi.kubevirt.io/storage.createdByController: "yes"
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: "false"
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    cdi.kubevirt.io: importer
    prometheus.cdi.kubevirt.io: "true"
  name: importer-prime-6baa5209-9d4a-4ded-a85f-a9ac1bf3fb2c
  namespace: virtualmachines
spec:
  containers:
  - name: importer
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: IMPORTER_SOURCE
      value: http
    - name: IMPORTER_ENDPOINT
      value: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
    - name: IMPORTER_CONTENTTYPE
      value: kubevirt
    - name: IMPORTER_IMAGE_SIZE
      value: "17043521016"
    - name: OWNER_UID
      value: 6baa5209-9d4a-4ded-a85f-a9ac1bf3fb2c
    - name: FILESYSTEM_OVERHEAD
      value: "0.055"
    - name: INSECURE_TLS
      value: "false"
    - name: IMPORTER_DISK_ID
    - name: IMPORTER_UUID
    - name: IMPORTER_PULL_METHOD
    - name: IMPORTER_READY_FILE
    - name: IMPORTER_DONE_FILE
    - name: IMPORTER_BACKING_FILE
    - name: IMPORTER_THUMBPRINT
    - name: http_proxy
    - name: https_proxy
    - name: no_proxy
    - name: IMPORTER_CURRENT_CHECKPOINT
    - name: IMPORTER_PREVIOUS_CHECKPOINT
    - name: IMPORTER_FINAL_CHECKPOINT
    - name: PREALLOCATION
      value: "false"
    - name: CACHE_MODE
    image: quay.io/kubevirt/cdi-importer:v1.59.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8443
      name: metrics
      protocol: TCP
    resources:
      limits:
        cpu: 750m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 60M
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 107
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: cdi-data-vol
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: virt2
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 107
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: cdi-data-vol
    persistentVolumeClaim:
      claimName: cdi-data-vol
```

And i can create files:

```
❯ k exec -it importer-prime-6baa5209-9d4a-4ded-a85f-a9ac1bf3fb2c -- /bin/bash
bash-5.1$ cd /data/
bash-5.1$ ls
lost+found
bash-5.1$ touch a
bash-5.1$ echo hello > a
bash-5.1$ cat a 
hello
bash-5.1$ 
```

**Comment by awels** [comment]
That is super weird, it is complaining about not being able to write there, and yet we just demonstrated it is entirely possible. I am missing the scratch space in your pod definition. At this point I want to essentially manually do what CDI does. Aka wget the qcow2 into the scratch space location, and then run the qemu-img convert to the target disk and see if that works.

**Comment by MichaelTrip** [comment]
> That is super weird, it is complaining about not being able to write there, and yet we just demonstrated it is entirely possible. I am missing the scratch space in your pod definition. At this point I want to essentially manually do what CDI does. Aka wget the qcow2 into the scratch space location, and then run the qemu-img convert to the target disk and see if that works.

The pod definition didn't include the scratch space pvc when i got the yaml from the pod. should i add it manually as a pvc and a volumeMount? 



> And just to be sure the created PVC from that DataVolumeTemplate has volumeMode: filesystem right? It is not a block volume?

I haven't specified a volumeMode in the `dataVolumeTemplate` 

```yaml
  dataVolumeTemplates:
    - metadata:
        name: debian-vm-iscsitest-pvc
        creationTimestamp: null
      spec:
        storage:
          resources:
            requests:
              storage: 15Gi
          accessModes:
            - ReadWriteMany
          storageClassName: synology-iscsi
        source:
          http:
            url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
```

As per documentation:

> volumeMode is an optional API parameter. Filesystem is the default mode used when volumeMode parameter is omitted.

It should use Filesystem by default, right ?
