### ISSUE TITLE
Cluster-wide importProxy CA certs option does not work

### ISSUE THREAD

**Issue by kreeuwijk** [kubevirt/containerized-data-importer#3684]
**What happened**:
When trying to configure cluster-wide trusted CA certs for any image imports, by setting the `importProxy. trustedCAProxy` parameter, the imports fail due to not getting the specified CA certs. Essentially [this code](https://github.com/kubevirt/containerized-data-importer/blob/v1.61.2/pkg/importer/registry-datasource.go#L184-L219) is not properly working in this scenario. I verified that the certificates do appear in a file in /proxycerts/, but the importer process does not seem to use it. Trying to get this to work is an endless chase of going through source code and contracting documentation, without getting any success. For example the documenation gives a `ca.pem` example for the configmap, but the source code reveals that only files with the `.crt` file extension will be used. But even when you use the `.crt` file extension, it still does not work.

If instead [this approach](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/image-from-registry.md#tls-certificate-configuration) is followed, the imports do work properly (and the documentation makes sense).

**What you expected to happen**:
If the `importProxy. trustedCAProxy` parameter is supposed to work, it should be fixed and correctly documented. If this method no longer is supported or maintained, it should be removed from the documentation and CRD.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure a proxy server with SSL inspection
2. Configure `importProxy. HTTPProxy`, `importProxy. HTTPSProxy` and `importProxy. noProxy` to force the importer to use the proxy. Note that imports fail due to the SSL inspection.
3. Grab the CA certs to trust, put them in a configmap in the `cdi` namespace and reference it with the `importProxy. trustedCAProxy` parameter in the CDIConfig.
4. Delete and recreate the datavolume to have it pick up the changes.
5. Notice the importer does get a `IMPORTER_PROXY_CERT_DIR` env variable assigned now, as well as a copy of the CA certs configmap in the namespace of the importer pod. But still the import fails due to the SSL inspection certificate not getting trusted.
6. Try  [this approach](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/image-from-registry.md#tls-certificate-configuration) instead and notice this does work correctly.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.61.2
- Kubernetes version (use `kubectl version`): 1.30.9
- DV specification:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "template-ubuntu-2204"
  namespace: "vmo-golden-images"
  annotations:
    cdi.kubevirt.io/storage.deleteAfterCompletion: "false"
    cdi.kubevirt.io/storage.bind.immediate.requested: ""
spec:
  storage:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 15Gi
    volumeMode: Block
  source:
    registry:
      url: "docker://gcr.io/spectro-images-public/release/vm-dashboard/os/ubuntu-container-disk:22.04"
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 24.04
- Kernel (e.g. `uname -a`): 6.8.0.55
- Install tools: N/A
- Others: N/A
