### ISSUE TITLE
Propagate DV Labels to Importer Pod test fails on s390x

### ISSUE THREAD

**Issue by Davo911** [kubevirt/containerized-data-importer#3781]
**What happened:**
When running[ these DV label inheritance tests](https://github.com/kubevirt/containerized-data-importer/blob/c8e5131bfe4b0664aa906c235129bb43aed16a3a/tests/import_test.go#L2107-L2154) on a s390x downstream cluster, the corresponding custom labels are not propagated to the importer pod.

Here when using an import populator, the cdi-controller creates a temporary prime- PVC to handle the data transfer. However, the custom labels from the original DataVolume are not copied to this temporary prime- PVC. Since the importer pod is created based on the metadata of this temporary PVC, it never inherits the labels. This breaks the label propagation chain.

**What you expected to happen:**
The importer pod should inherit all labels from the source DataVolume's metadata, regardless of whether a populator is used.

**How to reproduce it (as minimally and precisely as possible):**
Run one of these tests on a s390x D/S OpenShift cluster:
- `Propagate DV Labels to Importer Pod Import pod should inherit any labels from Data Volume [It] With Populators`
- `Propagate DV Labels to Importer Pod Import pod should inherit any labels from Data Volume [It] Without Populators`

**Additional context:**
- The DataVolume label-test is correctly created with the expected custom labels.
```
# From: oc get dv label-test -o yaml
metadata:
  labels:
    test.kubevirt.io/test: "true"
    testLabel: none
```
- The cdi-controller logs show that it creates a temporary PVC named prime-<uuid> to handle the import.
```
# From: oc logs -n openshift-cnv deployment/cdi-deployment
DEBUG   controller.import-controller  Creating importer POD for PVC {"pvc.Name": "prime-5bdbd32d-02ac-4135-ad17-3a72d4517a93"}
```
- Inspecting this prime-<uuid> PVC reveals that it lacks the custom labels from the source DataVolume. It only has the default CDI labels.
```
# From: oc get pvc prime-6849c1d9-ffd9-40da-b8f0-004ae40ae1e2 -o yaml
metadata:
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.19.0
    velero.io/exclude-from-backup: "true"
```
- The importer pod is then created from this prime-<uuid> PVC, and consequently does not have the labels to inherit.
- This issue occurs for both populators (usePopulator: "true") and legacy importers (usePopulator: "false").

**Environment:**
- CDI version: N/A
- Kubernetes version(Client/Server): 1.31.3/1.32.4
- Openshift version(Client/Server): 4.18.0/4.19.0
- OS (e.g. from /etc/os-release): Worker nodes are RHEL and RHCOS. 
- Kernel (e.g. uname -a): N/A
- Install tools: Deployed via OpenShift Operator.
- Arch: s390x
