### ISSUE TITLE
CDI pvc/datavolume with empty url won't have error message in PVC/importer-pod

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#418]
Description of problem:

Version-Release number of selected component (if applicable):

How reproducible:

Create PVC with empty URL and importer-pod won't be created, But PVC is bound, so there's no error message for the user except cdi controller log

Steps to Reproduce:
1. oc create -f pvc.yml  (pvc with empty cdi.kubevirt.io/storage.import.endpoint: "" )

Actual results:
PVC bound successfully, no importer-pod created 

Expected results:
Could we put some error messages to PVC or importer-pod?

Now I have to check cdi-controller log message
E0904 09:33:21.644152       1 import-controller.go:206] error processing pvc "kubevirt-test-default/test-resrouce-whshfgthkm": annotation "cdi.kubevirt.io/storage.import.endpoint" in pvc "kubevirt-test-default/test-resrouce-whshfgthkm" is empty
 

Additional info:

**Comment by j-griffith** [comment]
@shiywang could you share the pvc.yaml file you used?  I'd be interested in taking a look at reproducing this and see if I can fix it up.  Thanks!

**Comment by j-griffith** [comment]
@shiywang Could you provide the pvc.yaml file you used?  I'd be happy to take a closer look at this.

**Comment by shiywang** [comment]
> That seems to create the PVC but keep it in pending state "waiting for first consumer to be created before binding" which is what I'd expect. 

@j-griffith hi, that's the reason I filed an issue here. I also expected pvc could be pending or sth, but it bound successfully. the pvc file I use is 
```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: test-pvc
    annotations:
      cdi.kubevirt.io/storage.import.endpoint: ""
      cdi.kubevirt.io/storage.import.secretName: ""
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
```
