### ISSUE TITLE
DataVolume clone source doesn't set data volume phase properly.

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#455]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I have a working source PVC with some data in it.
I create a DV with source for instance like this:
```yaml
      source:
        pvc:
          name: template-test-dv-01
          namespace: default
```
It starts to clone the source PVC into my new DV and the cloning successfully completes. However it never updates the status of the DV to be Successful.
**What you expected to happen**:
The phase to be Successful instead of 'PVCBound', since everything completed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PVC called test-pvc in the default name space, and populate some data in it.
Then create a DV with this yaml
```yaml
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: "template-test-dv-01"
spec:
    source:
      pvc:
        name: test-pvc
        namespace: default
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "128Mi"
```
The process will complete but the status phase on the DV will remain PVCBound

**Anything else we need to know?**:
The functional tests did not catch this issue because it tests the contents of the target PVC (which are correct) and doesn't test for the phase of the DV.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
latest master
- Kubernetes version (use `kubectl version`):
1.10.4
- Cloud provider or hardware configuration:
- Install tools:
- Others:
