### ISSUE TITLE
re-creating a datavolume hangs forever

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#636]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

```
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  creationTimestamp: null
  name: dv1
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local
  source:
    http:
      url: http://cdi-http-import-server.kubevirt/images/alpine.iso
```

1. post the dv manifest above
2. allow dv to move to succeeded
3. delete dv
4. waith for dv and pvc/pv to be removed
5. re-post dv

At this point once the dv is re-posted, it will hang indefinitely. 

I see this log in the cdi controller which possibly indicates that an expectation has not been counted correctly.
```
I0205 18:31:21.475864       1 expectations.go:158] Controller still waiting on expectations &expectations.ControlleeExpectations{add:1, del:0, key:"default/dv1", timestamp:time.Time{wall:0xbf0e9375ad0831a7, ext:803602669659, loc:(*time.Location)(0x1bb0060)}}
```

**What you expected to happen**:

An identical dv should be able to be posted/deleted/posted multiple times. 

**Environment**:
- CDI version: **v1.5.1**
