### ISSUE TITLE
Request an Upload Token failed (BadRequest): error when creating "upload-datavolume-token.yaml"

### ISSUE THREAD

**Issue by Helenbj** [kubevirt/containerized-data-importer#876]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:

When I run command:

`kubectl apply -f manifests/example/upload-datavolume-token.yaml -o yaml`

the content of upload-datavolume-token.yaml is:

```
apiVersio apply -f manifests/example/upload-datavolume-token.yaml -o yamlload.cdi.kubevirt.io/v1alpha1
kind: UploadTokenRequest
metadata:
  name: upload-datavolume
  namespace: default
spec:
  pvcName: upload-datavolume
```

After run apply, the error output is：

`Error from server (BadRequest): error when creating "upload-datavolume-token.yaml": the server rejected our request for an unknown reason (post uploadtokenrequests.upload.cdi.kubevirt.io)`

**What you expected to happen**:

Get output as：

```
apiVersion: upload.cdi.kubevirt.io/v1alpha1
kind: UploadTokenRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"upload.cdi.kubevirt.io/v1alpha1","kind":"UploadTokenRequest","metadata":{"annotations":{},"name":"upload-datavolume-token","namespace":"default"},"spec":{"pvcName":"upload-datavolume"}}
  creationTimestamp: null
  name: upload-datavolume-token
  namespace: default
spec:
  pvcName: upload-datavolume
status:
  token: eyJhbGciOiJQUzUxMiIsImtpZCI6IiJ9.eyJwdmNOYW1lIjoidXBsb2FkLXRlc3QiLCJuYW1lc3BhY2UiOiJkZWZhdWx0IiwiY3JlYXRpb25UaW1lc3RhbXAiOiIyMDE4LTA5LTIxVDE4OjEyOjE5LjQwODI1MDQ4NFoifQ.JWk1VyvzSse3eFiBROKgGoLnOPCiYW9JdDWKXFROEL6XY0O5lFb1R0rwdfWwC3BBOtEA9mC9x3ZGYPnYWO-5G_r1fWKHjF-zifrCX_3Dhp3vfSq6Zfpu-vV0Qn0A3YkSCCmiC_nONAhVjEDuQsRFIKwYcxBoEOpye92ggH2u5FxQE7FwxxH6-RHun9tc_lIFX-ZFKnq7n5tWbjsTmAZI_4rDNgYkVFhFtENU6e-5_Ncokxs3YVzkbSrXweZpRmmaYQOmZhjXSLjKED_2FVq7tYeVueEEhKC_zJ-AEivstALPwPjiwyWXJyfE3dCmbA1sBKuNUrAaDlBvSAp1uPV9eQ
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):

`Error from server (NotFound): deployments.extensions "cdi-deployment" not found`

```
kubectl get deployments -n cdi
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
cdi-apiserver     1/1     1            1           13d
cdi-deployment    1/1     1            1           13d
cdi-operator      1/1     1            1           13d
cdi-uploadproxy   1/1     1            1           13d

```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Cenos 7

- Install tools:
kubeadm
- Others:

@ohadlevy  @mmazur @fabiand @booxter @MarSik I'm new to CDI, please help me out. Thank you!

**Comment by mhenriks** [comment]
Hi @Helenbj does the PVC `upload-datavolume` exist in the `default` namespace?  If not, change the namespace of the UploadTokenRequest accordingly.

**Comment by Helenbj** [comment]
@mhenriks Thanks for your reply, the upload-datavolume is also in default namespace.

I find I forget to run command:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-nodeport
  namespace: cdi
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 31001
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
EOF
```

However when I run command:

`kubectl port-forward -n cdi service/cdi-uploadproxy 8443:443`

I got an error output:

```
Forwarding from [::1]:8443 -> 8443
E0708 16:28:25.085396 4181988 portforward.go:233] lost connection to pod
```

If I ignore this and continue with `kubectl apply -f manifests/example/upload-datavolume.yaml`, the error output changes of command `kubectl apply -f manifests/example/upload-datavolume-token.yaml -o yaml`:

`Error from server (ServiceUnavailable): error when creating "upload-datavolume-token.yaml": the server is currently unable to handle the request (post uploadtokenrequests.upload.cdi.kubevirt.io)`

I think the problem is that I cannot Port forwarding via the API server correctly, but how to figure it out?
