### ISSUE TITLE
qemu-img 3.1 failing when trying to do stream conversions of cirros image

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/containerized-data-importer#914]
/kind bug

**What happened**:

When attempting to use the CDI importer to create a DataVolume (or a PVC directly) and specifying a cirros image, the conversion process hangs and never completes.

**What you expected to happen**:

The conversion process should either finish or fail, terminating the importer pod and providing me with a PVC that has the expected image on it (upon success).

**How to reproduce it (as minimally and precisely as possible)**:

Create a DV using the follwing yaml:

```
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: "fedora-datavol"
  annotations:
    kubevirt.io/provisionOnNode: kube-1
spec:
  source:
      http:
         url: "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
```
Then tail the logs on the importer pod and note the hang
