### ISSUE TITLE
DataVolume clone with source PVC using HostPath provisioner Unexpected Status Code 500

### ISSUE THREAD

**Issue by texascloud** [kubevirt/containerized-data-importer#955]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I'm trying to have 1 "golden" image which represents my blessed OSs from which I may create VMs. It would always start with the original golden image + stuff from the VM spec (cloud-init, etc). I cloned it once, and created and started a VM which used that as its `dataVolume`. When trying to run the exact same YAML but with a different name, I get this at the end of the importer Pod's logs every time. 
```
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  # This is the second time I'm running this. The first time the name was "ubuntu-test", and that one's importer Pod finished. Http source DataVolumes can be created, and one clone can be made, but it fails after anymore. Idk if it's related to the use of HostPath volumes ATM. Rook is giving me a pain
  name: ubuntu-copy
spec:
  source:
    pvc:
      namespace: default
      name: ubuntu16.04-golden-image
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        # ubuntu16.04-golden-image is 15GB and "storage" must be >=
        storage: 16Gi #.04 ayy
```

```
I0906 07:10:11.163271      10 prometheus.go:67] 96.69
I0906 07:10:12.163436      10 prometheus.go:67] 97.50
I0906 07:10:13.163619      10 prometheus.go:67] 98.29
I0906 07:10:14.163790      10 prometheus.go:67] 99.16
tar: ./disk.img: file changed as we read it
I0906 07:10:15.097712      10 clone-source.go:96] Wrote 10737428480 bytes
F0906 07:10:15.100777      10 clone-source.go:138] Unexpected status code 500
goroutine 1 [running]:
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.stacks(0xc0002d9200, 0xc0002fc000, 0x4e, 0xa3)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:828 +0xd4
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.(*loggingT).output(0x1a61600, 0xc000000003, 0xc00011a840, 0x19f6b9f, 0xf, 0x8a, 0x0)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:779 +0x306
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.(*loggingT).printf(0x1a61600, 0xc000000003, 0x1034403, 0x19, 0xc0004fdf08, 0x1, 0x1)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:678 +0x14b
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.Fatalf(0x1034403, 0x19, 0xc0004fdf08, 0x1, 0x1)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:1207 +0x67
main.main()
        /go/src/kubevirt.io/containerized-data-importer/cmd/cdi-cloner/clone-source.go:138 +0x88b
```

Here's the [HostPath provisioner](https://github.com/kubevirt/kubevirt/blob/master/docs/devel/hostpath-provisioner.yaml) I mentioned:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-provisioner
  labels:
    app: hostpath-provisioner
spec:
  selector:
    matchLabels:
      app: hostpath-provisioner
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: hostpath-provisioner
    spec:
      serviceAccount: hostpath-sa
      serviceAccountName: hostpath-sa
      containers:
        - name: hostpath-provisioner
          image: kubevirtdevelstorage/hostpath-provisioner:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PV_DIR
              value: /var/run/kubevirt/hostpath
          volumeMounts:
            - name: pv-volume
              mountPath: /var/run/kubevirt/hostpath
      volumes:
        - name: pv-volume
          hostPath:
            path: /var/run/kubevirt/hostpath

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hostpath-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostpath-provisioner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostpath-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hostpath-provisioner
subjects:
- kind: ServiceAccount
  name: hostpath-sa
  namespace: default
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kubevirt
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: hostpath
```
I tried creating a DataVolume that used a PVC as its source, but it's failing. Maybe something to do with already having made another DataVolume which cloned it. I don't know why this would matter.
**What you expected to happen**:
I sorta explained above
**How to reproduce it (as minimally and precisely as possible)**:
Read above
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
`image: kubevirt/cdi-operator:v1.10.3`

- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
OS: Ubuntu 16.04 xenial
 Kernel: x86_64 Linux 4.4.0-116-generic
 CPU: 2x Intel Xeon CPU E5-2660 0 @ 3GHz
 RAM: 5723MiB / 193417MiB
```

- Others:
```
KUBEVIRT_VERSION:        v0.20.4
```
